#!/usr/bin/env python3
"""Writes a C source holding a binary file as an array (the 3DS build's
picasso shader binaries): embed_binary.py <input> <output.c|.h> <name>.
A .c output defines `const unsigned char NAME[]` and `const unsigned NAME_size`
with external linkage; a .h output defines them static in the header."""
import sys
from pathlib import Path

data = Path(sys.argv[1]).read_bytes()
name = sys.argv[3]
header = sys.argv[2].endswith(".h")
storage = "static " if header else ""
lines = ["/* Generated by tools/n3ds/embed_binary.py from %s. Do not edit. */" % Path(sys.argv[1]).name]
lines += ["#pragma once"] if header else []
lines += ["%sconst unsigned char %s[] __attribute__((aligned(4))) = {" % (storage, name)]
for i in range(0, len(data), 16):
    lines.append("\t" + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
lines += ["};", "%sconst unsigned %s_size = %d;" % (storage, name, len(data)), ""]
Path(sys.argv[2]).write_text("\n".join(lines))
