#! /usr/bin/env python
# encoding: utf-8

# RFC 0027 sample tools: small programs on the public libraries only. None
# links the kiln application or starts a kiln process.

def options(opt):
	return

def configure(conf):
	conf.load('strict_cpp20', tooldir='scripts/waifulib')

def build(bld):
	strict = bld.strict_cpp20_env()
	bld.program(env=strict, source=['play_embedded/play_embedded.cpp'], target='play_embedded/play_embedded_sample',
		name='play_embedded', arch_module='kiln.samples', features='cxx cxxprogram',
		includes=['../../public'],
		use=['kiln_core', 'product_toolchain_linux', 'product_stage_waf', 'product_package_linux_dir',
			'product_display_desktop', 'product_run_desktop', 'platform_posix', 'jobsystem'],
		install_path=None, subsystem='CONSOLE')
