#! /usr/bin/env python
# encoding: utf-8

PROJECT_NAME = 'vvis'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS != 'linux':
		bld.fatal('the vvis host-tool profile is currently validated only on Linux')

	bld(
		source = [
			'vvis.cpp',
			'flow.cpp',
			'WaterDist.cpp',
			'../../public/collisionutils.cpp',
			'../../public/loadcmdline.cpp',
			'../../public/lumpfiles.cpp',
			'../../filesystem/linux_support.cpp',
			'../lzma/lzma.cpp',
			'../lzma/C/LzmaEnc.c',
			'../lzma/C/LzFind.c',
			'../common/bsplib.cpp',
			'../common/cmdlib.cpp',
			'../common/cmdlib_linux.cpp',
			'../../public/filesystem_helpers.cpp',
			'../../public/filesystem_init.cpp',
			'../common/filesystem_tools.cpp',
			'../common/pacifier.cpp',
			'../common/scriplib.cpp',
			'../common/threads_linux.cpp',
			'../common/tools_minidump_linux.cpp',
			'../../public/zip_utils.cpp',
		],
		target = PROJECT_NAME,
		name = PROJECT_NAME,
		features = 'cxx cxxprogram',
		includes = [ '.', '../../public', '../../public/tier0', '../../public/tier1',
			'../common', '../vmpi', '../../common', '../../thirdparty' ],
		defines = [ 'MACRO_MATHLIB', 'PROTECTED_THINGS_DISABLE', '_LZMA_PROB32', '_7ZIP_ST' ],
		use = [ 'mathlib', 'tier0', 'tier1', 'tier2', 'vstdlib', 'vtf', 'bitmap' ],
		ldflags = [ '-Wl,-Bstatic', '-Lbitmap', '-lbitmap', '-Wl,-Bdynamic' ],
		rpath = [ '$ORIGIN/bin' ],
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
