//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: The content hash (FNV-1a 64 over the bytes) and GLSL source of
//          every array in material_spv.h, so the backend names the shader
//          modules it creates and matches debug variants to them
//          (vulkan_shader_library.cpp). GENERATED by
//          shaders/regen_material_spv.py with material_spv.h; do not edit.
//
//===========================================================================//

#ifndef SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H
#define SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H

#include <cstdint>

struct MaterialSpvIndexEntry
{
	uint64_t hash;
	const char *array;
	const char *source; // the GLSL file and its compile options
};

static const MaterialSpvIndexEntry g_materialSpvIndex[] = {
    { 0x6be9899c229c6183ull, "g_materialTexVertSpv", "demo_dyn_tex.vert" },
    { 0x6c148c800879213eull, "g_materialTexClipVertSpv", "demo_dyn_tex.vert -DCLIP_PLANES" },
    { 0xf6f4ee6383b11fe7ull, "g_worldMeshVertSpv", "world_mesh.vert" },
    { 0x2bf7ebc87e534f58ull, "g_worldMeshClipVertSpv", "world_mesh.vert -DCLIP_PLANES" },
    { 0xc98ef2abdbb342f6ull, "g_worldPbrVertSpv", "world_pbr.vert" },
    { 0x2981e4a64dd01abcull, "g_worldPbrClipVertSpv", "world_pbr.vert -DCLIP_PLANES" },
    { 0xea38068e92db33d2ull, "g_worldPbrFragSpv", "world_pbr.frag" },
    { 0xd4a5911b68b73439ull, "g_worldPbrClipFragSpv", "world_pbr.frag -DCLIP_PLANES" },
    { 0xf8c73026f0562847ull, "g_worldPbrIndirectFragSpv", "world_pbr.frag -DINDIRECT_VIEW" },
    { 0x800b89d2989a57c2ull, "g_worldPbrLightFragSpv", "world_pbr.frag -DDIRECT_LIGHTS" },
    { 0x91543ffb8a611006ull, "g_worldPbrLightClipFragSpv",
        "world_pbr.frag -DDIRECT_LIGHTS -DCLIP_PLANES" },
    { 0x47b33ecebbf5162eull, "g_worldPbrRuntimeFragSpv", "world_pbr.frag -DRUNTIME_INDIRECT" },
    { 0xcac45bd99c235985ull, "g_worldPbrRuntimeClipFragSpv",
        "world_pbr.frag -DRUNTIME_INDIRECT -DCLIP_PLANES" },
    { 0x3b774e80df974687ull, "g_worldPbrLightRuntimeFragSpv",
        "world_pbr.frag -DDIRECT_LIGHTS -DRUNTIME_INDIRECT" },
    { 0x079b7ec2012ca9c9ull, "g_worldPbrLightRuntimeClipFragSpv",
        "world_pbr.frag -DDIRECT_LIGHTS -DRUNTIME_INDIRECT -DCLIP_PLANES" },
    { 0x3f3231e0692ddf13ull, "g_worldPbrIndirectClipFragSpv",
        "world_pbr.frag -DINDIRECT_VIEW -DCLIP_PLANES" },
    { 0xf36d92be4646a02aull, "g_worldPbrDeltaFragSpv", "world_pbr.frag -DDELTA_VOLUME" },
    { 0xadaf8e9926dcb25full, "g_worldPbrDeltaClipFragSpv",
        "world_pbr.frag -DDELTA_VOLUME -DCLIP_PLANES" },
    { 0x1f48939e32555e6cull, "g_worldPbrLightDeltaFragSpv",
        "world_pbr.frag -DDIRECT_LIGHTS -DDELTA_VOLUME" },
    { 0x0e81dce154255430ull, "g_worldPbrLightDeltaClipFragSpv",
        "world_pbr.frag -DDIRECT_LIGHTS -DDELTA_VOLUME -DCLIP_PLANES" },
    { 0xe188bcf03acf025aull, "g_worldPbrIndirectDeltaFragSpv",
        "world_pbr.frag -DINDIRECT_VIEW -DDELTA_VOLUME" },
    { 0x3c6a4e102d706fdbull, "g_worldPbrIndirectDeltaClipFragSpv",
        "world_pbr.frag -DINDIRECT_VIEW -DDELTA_VOLUME -DCLIP_PLANES" },
    { 0x2f8a9e6d376b11d5ull, "g_computeFillSpv", "compute_fill.comp" },
    { 0x974a4ae6f40baa18ull, "g_sdfProbeTraceSpv", "sdf_probe_trace.comp" },
    { 0x2f0efeaaeb8c4a5cull, "g_reflectionProbesCheckSpv", "reflection_probes_check.comp" },
    { 0x710848e76f097403ull, "g_rayQueryProbeTraceSpv",
        "sdf_probe_trace.comp --target-env=vulkan1.2 -DRAY_QUERY" },
    { 0x40b02fe6c2189a0dull, "g_worldGlassFragSpv", "world_pbr_glass.frag" },
    { 0x7c1afaefe9504203ull, "g_worldGlassClipFragSpv", "world_pbr_glass.frag -DCLIP_PLANES" },
    { 0x8e24c6fffe7fe02eull, "g_materialTexFragSpv", "demo_dyn_tex.frag" },
    { 0x338bd5846a70b2c3ull, "g_portalRefractVertSpv", "portal_refract.vert" },
    { 0xca94d06aa10f5fb2ull, "g_portalRefractFragSpv", "portal_refract.frag" },
    { 0x1c74736c36f6158full, "g_skinVertSpv", "skin.vert" },
    { 0x805129cbcdc2377dull, "g_skinFragSpv", "skin.frag" },
    { 0xbe69f7e7d0ff207full, "g_lightmappedVertSpv", "lightmapped.vert" },
    { 0x07c2415caa00b291ull, "g_lightmappedFragSpv", "lightmapped.frag" },
    { 0x7885880da22ed564ull, "g_postVertSpv", "screenspace_post.vert" },
    { 0xd0c7bf251ecd16d1ull, "g_postFragSpv", "screenspace_post.frag" },
    { 0x812291b1a04701a2ull, "g_solidEnergyVertSpv", "solidenergy.vert" },
    { 0xc8fe3e07584fd149ull, "g_solidEnergyFragSpv", "solidenergy.frag" },
    { 0x4e785057198a28c5ull, "g_paintBlobFragSpv", "paintblob.frag" },
    { 0x71bd53ea70030837ull, "g_lightmappedPaintFragSpv", "lightmappedpaint.frag" },
    { 0xdf11cc5f1a1ebec9ull, "g_modelPbrFragSpv", "model_pbr.frag" },
    { 0x7d37989aef3562d1ull, "g_modelPbrEnvFragSpv", "model_pbr.frag -DENV_CUBE" },
    { 0xd135e65d37455cc8ull, "g_modelPbrIndirectFragSpv", "model_pbr.frag -DINDIRECT_VIEW" },
    { 0x32a8a1de5ed5acdaull, "g_modelPbrProbeFragSpv", "model_pbr.frag -DPROBE_VOLUME" },
    { 0x0c88688c1f15b113ull, "g_modelPbrEnvProbeFragSpv",
        "model_pbr.frag -DENV_CUBE -DPROBE_VOLUME" },
    { 0x2f1d88c69d83d941ull, "g_modelPbrIndirectProbeFragSpv",
        "model_pbr.frag -DINDIRECT_VIEW -DPROBE_VOLUME" },
    { 0xabb75cd64f4600adull, "g_pbrDirectFragSpv", "pbr_direct.frag" },
    { 0xceab061f59287ab6ull, "g_pbrDirectClipFragSpv", "pbr_direct.frag -DCLIP_PLANES" },
    { 0xe2b8e6ce9f238241ull, "g_pbrBrdfCheckSpv", "pbr_brdf_check.comp" },
    { 0xc0c5d25866bef879ull, "g_presentGammaVertSpv", "present_gamma.vert" },
    { 0x577895e15ac25eb0ull, "g_presentGammaFragSpv", "present_gamma.frag" },
};

// X( array ) for every array, for suites that include material_spv.h.
#define MATERIAL_SPV_ARRAYS( X )                                                                   \
	X( g_materialTexVertSpv )                                                                      \
	X( g_materialTexClipVertSpv )                                                                  \
	X( g_worldMeshVertSpv )                                                                        \
	X( g_worldMeshClipVertSpv )                                                                    \
	X( g_worldPbrVertSpv )                                                                         \
	X( g_worldPbrClipVertSpv )                                                                     \
	X( g_worldPbrFragSpv )                                                                         \
	X( g_worldPbrClipFragSpv )                                                                     \
	X( g_worldPbrIndirectFragSpv )                                                                 \
	X( g_worldPbrLightFragSpv )                                                                    \
	X( g_worldPbrLightClipFragSpv )                                                                \
	X( g_worldPbrRuntimeFragSpv )                                                                  \
	X( g_worldPbrRuntimeClipFragSpv )                                                              \
	X( g_worldPbrLightRuntimeFragSpv )                                                             \
	X( g_worldPbrLightRuntimeClipFragSpv )                                                         \
	X( g_worldPbrIndirectClipFragSpv )                                                             \
	X( g_worldPbrDeltaFragSpv )                                                                    \
	X( g_worldPbrDeltaClipFragSpv )                                                                \
	X( g_worldPbrLightDeltaFragSpv )                                                               \
	X( g_worldPbrLightDeltaClipFragSpv )                                                           \
	X( g_worldPbrIndirectDeltaFragSpv )                                                            \
	X( g_worldPbrIndirectDeltaClipFragSpv )                                                        \
	X( g_computeFillSpv )                                                                          \
	X( g_sdfProbeTraceSpv )                                                                        \
	X( g_reflectionProbesCheckSpv )                                                                \
	X( g_rayQueryProbeTraceSpv )                                                                   \
	X( g_worldGlassFragSpv )                                                                       \
	X( g_worldGlassClipFragSpv )                                                                   \
	X( g_materialTexFragSpv )                                                                      \
	X( g_portalRefractVertSpv )                                                                    \
	X( g_portalRefractFragSpv )                                                                    \
	X( g_skinVertSpv )                                                                             \
	X( g_skinFragSpv )                                                                             \
	X( g_lightmappedVertSpv )                                                                      \
	X( g_lightmappedFragSpv )                                                                      \
	X( g_postVertSpv )                                                                             \
	X( g_postFragSpv )                                                                             \
	X( g_solidEnergyVertSpv )                                                                      \
	X( g_solidEnergyFragSpv )                                                                      \
	X( g_paintBlobFragSpv )                                                                        \
	X( g_lightmappedPaintFragSpv )                                                                 \
	X( g_modelPbrFragSpv )                                                                         \
	X( g_modelPbrEnvFragSpv )                                                                      \
	X( g_modelPbrIndirectFragSpv )                                                                 \
	X( g_modelPbrProbeFragSpv )                                                                    \
	X( g_modelPbrEnvProbeFragSpv )                                                                 \
	X( g_modelPbrIndirectProbeFragSpv )                                                            \
	X( g_pbrDirectFragSpv )                                                                        \
	X( g_pbrDirectClipFragSpv )                                                                    \
	X( g_pbrBrdfCheckSpv )                                                                         \
	X( g_presentGammaVertSpv )                                                                     \
	X( g_presentGammaFragSpv )

#endif // SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H
