#! /usr/bin/env python
# encoding: utf-8
# render.renderer (RFC 0016); edges in architecture/modules.json.

def build(bld):
	bld.stlib(
		env         = bld.strict_cpp20_env(),
		features    = 'cxx capability_strict',
		arch_module = 'render.renderer',
		target      = 'render_renderer',
		name        = 'render_renderer',
		source      = bld.path.ant_glob('*.cpp'),
		includes    = ['../../public'],
		use         = ['render_frame', 'render_graph', 'render_device'],
		idx         = bld.get_taskgen_count()
	)
