#!/usr/bin/env python3
"""Frozen VGUI ABI vtable tables (RFC 0010 V0 check `legacy.vgui-abi`).

    python3 tools/vgui/vgui_abi.py check
    python3 tools/vgui/vgui_abi.py record [--update]
    python3 tools/vgui/vgui_abi.py sensitivity [--cxx g++] [--out DIR]

RFC 0010 keeps VGUI's public API frozen while its machinery is rebuilt
beneath it. This table holds that promise mechanically for the interfaces
that cross a module boundary: the versioned interfaces game and tool modules
obtain from vgui2 and vguimatsurface, and the interfaces a module hands
across that boundary for the other side to call (IClientPanel, implemented
by every vgui_controls panel and called by vgui2; the scheme's borders and
images; the HTML window and its events; the material info objects).

The recorded table, quality/fixtures/vgui-abi/vgui_abi_v1.h, lists every
vtable slot of each interface in Itanium (Linux x86_64) order, with the
interface version string where one is defined. The conformance suite
(unittests/vguiabitest/vgui_abi_conformance.cpp, compiled in the
legacy-cxx11 dialect) includes it and derives each slot from the compiler's
own pointer-to-member-function value.

Commands, oracles and the sensitivity seeds are those of
tools/quality/abi_table.py, shared with the render table
(tools/render/render_abi.py); this file holds the VGUI table's
specification. `record --update` is a reviewed ABI decision, never a way to
make a check pass.

Not in the table: VGuiWorldPanelRecorder001 (public/vgui/IWorldPanelRecorder.h)
is a first-party interface added for RFC 0016's in-world panels, not part of
the frozen surface; vgui_controls is a static library compiled into each
consumer, so its classes are a source API, not a cross-module ABI.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools", "quality"))
import abi_table  # noqa: E402  (the shared table machinery)

TABLE_VERSION = "vgui-abi-v1"
TABLE = "quality/fixtures/vgui-abi/vgui_abi_v1.h"
SUITE_ID = "legacy.vgui-abi"

# (id, C++ type, header under public/, interface version macro or None).
# Order is the table's order.
INTERFACES = [
    ("ISurface", "vgui::ISurface", "vgui/ISurface.h", "VGUI_SURFACE_INTERFACE_VERSION"),
    ("IMatSystemSurface", "IMatSystemSurface", "VGuiMatSurface/IMatSystemSurface.h",
     "MAT_SYSTEM_SURFACE_INTERFACE_VERSION"),
    ("IPanel", "vgui::IPanel", "vgui/IPanel.h", "VGUI_PANEL_INTERFACE_VERSION"),
    ("IClientPanel", "vgui::IClientPanel", "vgui/IClientPanel.h", None),
    ("IVGui", "vgui::IVGui", "vgui/IVGui.h", "VGUI_IVGUI_INTERFACE_VERSION"),
    ("ISchemeManager", "vgui::ISchemeManager", "vgui/IScheme.h", "VGUI_SCHEME_INTERFACE_VERSION"),
    ("IScheme", "vgui::IScheme", "vgui/IScheme.h", None),
    ("IBorder", "vgui::IBorder", "vgui/IBorder.h", None),
    ("IImage", "vgui::IImage", "vgui/IImage.h", None),
    ("IInput", "vgui::IInput", "vgui/IInput.h", "VGUI_INPUT_INTERFACE_VERSION"),
    ("IInputInternal", "vgui::IInputInternal", "vgui/IInputInternal.h",
     "VGUI_INPUTINTERNAL_INTERFACE_VERSION"),
    ("ISystem", "vgui::ISystem", "vgui/ISystem.h", "VGUI_SYSTEM_INTERFACE_VERSION"),
    ("ILocalize", "ILocalize", "tier1/ilocalize.h", "VGUI_LOCALIZE_INTERFACE_VERSION"),
    ("IHTML", "vgui::IHTML", "vgui/IHTML.h", None),
    ("IHTMLEvents", "vgui::IHTMLEvents", "vgui/IHTML.h", None),
    ("IVguiMatInfo", "IVguiMatInfo", "vgui/IVguiMatInfo.h", None),
    ("IVguiMatInfoVar", "IVguiMatInfoVar", "vgui/IVguiMatInfoVar.h", None),
]

# VGUI_LOCALIZE_INTERFACE_VERSION is defined beside vgui::ILocalize, not in
# tier1/ilocalize.h, which declares the class.
EXTRA_INCLUDES = ["vgui/ILocalize.h"]

PREAMBLE = [
    "//========= Copyright Valve Corporation, All rights reserved. ============//",
    "//",
    "// Recorded vtable table %s of the frozen VGUI interfaces (RFC 0010 V0," % TABLE_VERSION,
    "// check legacy.vgui-abi). Itanium ABI, Linux x86_64. Generated by",
    "// `python3 tools/vgui/vgui_abi.py record` from clang's vtable layout dump;",
    "// reviewed and never regenerated to make a check pass. A change here is an",
    "// ABI break of every prebuilt consumer of these interfaces.",
    "//",
    "// X-macro list, included twice by",
    "// unittests/vguiabitest/vgui_abi_conformance.cpp:",
    "//   VGUI_ABI_INTERFACE( I, Type, header, slots ) primary vtable function slots",
    "//   VGUI_ABI_VERSION( I, MACRO, value )          interface version string",
    "//   VGUI_ABI_METHOD( I, adj, slot, signature, Declarer, Name, PmfDeclaration )",
    "//   VGUI_ABI_DESTRUCTOR( I, adj, slot, kind )",
    "//   VGUI_ABI_SECONDARY( I, Base, adj, slots )    secondary vtable of Base",
    "//   VGUI_ABI_END( I )",
    "// `I` names the interface in the table and in failure lines; `Type` is its",
    "// C++ type. `adj` is the this-adjustment of a call through a Type*, `slot`",
    "// the function index in the vtable that adjustment selects. PmfDeclaration",
    "// declares VguiAbiPmf, the member pointer type of the recorded signature;",
    "// it is resolved inside namespace vgui, in a class derived from Declarer,",
    "// where the declarer's nested types and protected members are visible.",
    "// Signatures print types as clang does; a declaring class at global scope",
    "// is written ::C so it cannot bind to a vgui namesake (vgui::ILocalize).",
    "//=============================================================================//",
]

SPEC = abi_table.Spec(TABLE_VERSION, TABLE, SUITE_ID, "VGUI_ABI", "VguiAbi", "VguiAbiPmf",
                      "VguiAbiSeededExtra", INTERFACES, PREAMBLE, typed=True,
                      extra_includes=EXTRA_INCLUDES, qualify_global=True)


def main(argv=None):
    return abi_table.main(SPEC, argv, description=__doc__.split("\n\n")[0], root=ROOT)


if __name__ == "__main__":
    sys.exit(main())
