#! /usr/bin/env python
# encoding: utf-8
# Toolchain-recorder fixture (b): commands that compile without `build`
# (`waf install`), partial builds (--targets) and failed builds. Two installed
# targets; --fixture-define changes every compile argv, and
# --fixture-define=FIXTURE_BREAK makes beta.cpp fail to compile.

import os

top = '.'
out = 'build'
TOOLS = os.environ['TOOLCHAIN_FIXTURE_REPO'] + '/quality/fixtures/corpus/toolchain'


def options(opt):
	opt.load('recorder_fixture', tooldir=TOOLS)


def configure(conf):
	conf.load('recorder_fixture', tooldir=TOOLS)


def build(bld):
	defines = bld.options.FIXTURE_DEFINES
	bld(features='cxx cxxshlib', source='alpha.cpp', target='alpha', defines=defines,
		install_path='${PREFIX}/lib')
	bld(features='cxx cxxprogram', source='beta.cpp', target='beta', defines=defines,
		install_path='${PREFIX}/bin')
