#! /usr/bin/env python
# encoding: utf-8

top = '.'
PROJECT_NAME = 'appsystemgrouptest'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	bld.program(
		source       = [ 'appsystemgrouptest.cpp' ],
		target       = PROJECT_NAME,
		name         = PROJECT_NAME,
		features     = 'c cxx cxxprogram',
		includes     = [ '../../public' ],
		defines      = [],
		use          = [ 'appframework', 'tier0', 'tier1', 'vstdlib' ],
		lib          = [ 'dl' ] if bld.env.DEST_OS != 'win32' else [],
		install_path = bld.env.TESTDIR,
		subsystem    = bld.env.MSVC_SUBSYSTEM,
		idx          = bld.get_taskgen_count()
	)
	bld.program(
		source       = [ 'dedicatedcompositiontest.cpp' ],
		target       = 'dedicatedcompositiontest',
		name         = 'dedicatedcompositiontest',
		features     = 'c cxx cxxprogram',
		includes     = [ '../../public', '../../public/tier1', '../..' ],
		use          = [ 'dedicated_composition_bridge', 'appframework', 'tier0', 'tier1', 'vstdlib' ],
		lib          = [ 'dl' ] if bld.env.DEST_OS != 'win32' else [],
		install_path = bld.env.TESTDIR,
		subsystem    = bld.env.MSVC_SUBSYSTEM,
		idx          = bld.get_taskgen_count()
	)
