#! /usr/bin/env python
# encoding: utf-8
# render.culling (RFC 0016 layer 5 mechanism, GPU-driven submission S3/S4).

def build(bld):
	bld.stlib(
		env         = bld.strict_cpp20_env(),
		features    = 'cxx capability_strict',
		arch_module = 'render.culling',
		target      = 'render_culling',
		name        = 'render_culling',
		source      = bld.path.ant_glob('*.cpp'),
		includes    = ['../../public'],
		use         = ['render_scene', 'render_graph', 'render_device', 'render_shaderlib', 'render_spv'],
		idx         = bld.get_taskgen_count()
	)
