# encoding: utf-8
# static_composition.py -- link every first-party module into one image
#
# iOS products link first-party modules statically (AGENTS.md "Platform-compliant
# composition"). --static-composition builds each first-party shared library of
# the product as a *module object* instead: one relocatable object that keeps
# shared-library symbol isolation, and links the product's programs from them.
#
# A module object is the module's own objects plus the first-party static
# libraries it links privately (tier1, mathlib, ...), partially linked with
# `-r`. Symbols the module did not export (hidden visibility) become local, so
# each module keeps its own copy of its private libraries, globals, interface
# registry and inline functions, exactly as when it was a shared library.
# COMDAT groups are dissolved in the partial link so the final link cannot
# fold one module's inline functions into another module's.
#
# Only exported (default visibility) symbols stay global. Every module's
# CreateInterface is hidden in this configuration (public/tier1/interface.h);
# each module object instead exports one uniquely named adapter,
# StaticModule_<target>_CreateInterface, generated below. Composition roots
# reach modules through those named entries and typed linked functions, never
# by filename or dlopen.
#
# Consumers never link another module object into their own: module objects
# reach only the product's programs, which link the closure of module objects
# they use, foundation first, plus the system libraries those modules use.

import os
import re

from waflib import Errors, Logs, Task, Utils
from waflib.TaskGen import after_method, before_method, feature
from waflib.Tools import ccroot

MODULE_ENTRY_TEMPLATE = '''// Generated by scripts/waifulib/static_composition.py. Do not edit.
// The named entry of module '%(target)s' in a statically composed product.
extern "C" void *CreateInterface( const char *pName, int *pReturnCode );

extern "C" __attribute__(( visibility( "default" ) )) void *%(entry)s(
	const char *pName, int *pReturnCode )
{
	return CreateInterface( pName, pReturnCode );
}
'''


def options(opt):
	grp = opt.add_option_group('Common options')
	grp.add_option('--static-composition', action='store_true', dest='STATIC_COMPOSITION',
		default=False, help='link every first-party module statically into the product '
		'programs (the Apple composition policy)')


def configure(conf):
	conf.env.STATIC_COMPOSITION = bool(getattr(conf.options, 'STATIC_COMPOSITION', False))
	if conf.env.DEST_OS in ('darwin', 'ios') and not conf.env.STATIC_COMPOSITION:
		conf.fatal('Apple products are statically composed; configure with --static-composition')
	if not conf.env.STATIC_COMPOSITION:
		return
	if conf.env.DEST_OS == 'win32' or conf.env.COMPILER_CXX == 'msvc':
		conf.fatal('--static-composition needs an ELF or Mach-O toolchain')
	if conf.env.DEST_BINFMT == 'mac-o':
		# ld64 -r turns hidden (private extern) symbols into local ones itself;
		# LLVM's ld64.lld does not implement -r. The iOS toolchain provides
		# Apple's ld64 (cctools-port); see tools/ios/build_toolchain.py.
		conf.find_program(['ld64', 'aarch64-apple-darwin-ld'], var='LD64')
		conf.env.LD64_ARCH = {'aarch64': 'arm64', 'arm64': 'arm64',
			'x86_64': 'x86_64', 'amd64': 'x86_64'}.get(conf.env.DEST_CPU, conf.env.DEST_CPU)
	elif conf.env.DEST_BINFMT == 'wasm':
		# wasm-ld --relocatable, then wasm_localize.py for --localize-hidden.
		pass
	else:
		conf.find_program('objcopy', var='OBJCOPY')
	conf.env.append_unique('DEFINES', ['SOURCE_STATIC_COMPOSITION=1'])
	if conf.env.COMPILER_CC == 'gcc':
		# GCC gives static locals of inline functions STB_GNU_UNIQUE binding,
		# which --localize-hidden leaves global; weak hidden ones are localized.
		conf.env.append_unique('CFLAGS', ['-fno-gnu-unique'])
		conf.env.append_unique('CXXFLAGS', ['-fno-gnu-unique'])
	conf.env.cxxmodule_PATTERN = 'lib%s.o'


def module_entry_name(target):
	"""The exported entry of a module object; the target name made an identifier."""
	return 'StaticModule_%s_CreateInterface' % re.sub(r'[^0-9A-Za-z_]', '_', target)


class cxxmodule(ccroot.link_task):
	"""Partially links a module's objects and private static libraries into one
	relocatable object with shared-library symbol isolation."""
	color = 'YELLOW'
	inst_to = None
	chmod = Utils.O644

	def keyword(self):
		return 'Linking module object'

	def run(self):
		env = self.env
		if env.DEST_BINFMT == 'mac-o':
			return self.run_macho()
		if env.DEST_BINFMT == 'wasm':
			return self.run_wasm()
		output = self.outputs[0].abspath()
		partial = output + '.partial'
		cmd = Utils.to_list(env.LINK_CXX) + ['-r', '-nostdlib', '-Wl,--force-group-allocation']
		cmd += [node.abspath() for node in self.inputs]
		for path in self.private_stlib_paths:
			cmd += ['-L' + path]
		cmd += ['-Wl,-Bstatic', '-Wl,--start-group']
		cmd += ['-l' + name for name in self.private_stlibs]
		cmd += ['-Wl,--end-group', '-o', partial]
		ret = self.exec_command(cmd)
		if ret:
			return ret
		ret = self.exec_command(Utils.to_list(env.OBJCOPY) + ['--localize-hidden', partial, output])
		try:
			os.remove(partial)
		except OSError:
			pass
		return ret

	def run_wasm(self):
		# wasm-ld has no group allocation flag; wasm_localize drops the COMDAT
		# groups instead, along with making hidden symbols local.
		import wasm_localize
		env = self.env
		output = self.outputs[0].abspath()
		partial = output + '.partial'
		cmd = Utils.to_list(env.LINK_CXX) + ['-r', '-nostdlib']
		cmd += [node.abspath() for node in self.inputs]
		for path in self.private_stlib_paths:
			cmd += ['-L' + path]
		cmd += ['-Wl,--start-group'] + ['-l' + name for name in self.private_stlibs]
		cmd += ['-Wl,--end-group', '-o', partial]
		ret = self.exec_command(cmd)
		if ret:
			return ret
		try:
			with open(partial, 'rb') as source:
				data, _ = wasm_localize.localize_hidden(source.read())
			with open(output, 'wb') as target:
				target.write(data)
		except (OSError, wasm_localize.WasmError) as error:
			Logs.error('%s: %s' % (output, error))
			return 1
		finally:
			try:
				os.remove(partial)
			except OSError:
				pass
		return 0

	def run_macho(self):
		# ld64 searches archives until no undefined symbol can be resolved, so
		# no group is needed; hidden symbols come out local ("was a private
		# external").
		env = self.env
		cmd = Utils.to_list(env.LD64) + ['-r', '-arch', env.LD64_ARCH]
		cmd += [node.abspath() for node in self.inputs]
		for path in self.private_stlib_paths:
			cmd += ['-L' + path]
		cmd += ['-l' + name for name in self.private_stlibs]
		cmd += ['-o', self.outputs[0].abspath()]
		return self.exec_command(cmd)


def _is_module(tg):
	if getattr(tg, 'link_task', None) is not None:
		return isinstance(tg.link_task, cxxmodule)
	features = tg.to_list(getattr(tg, 'features', []))
	return 'cshlib' in features or 'cxxshlib' in features


def _private_closure(self):
	"""Task generators a module links privately: those reached from its use list
	without passing through another module."""
	found, seen = [], set()
	pending = list(self.to_list(getattr(self, 'use', [])))
	while pending:
		name = pending.pop(0)
		if name in seen:
			continue
		seen.add(name)
		tg = _tgen(self.bld, name)
		if tg is None or _is_module(tg):
			continue
		found.append(tg)
		pending.extend(tg.to_list(getattr(tg, 'use', [])))
	return found


def _tgen(bld, name):
	try:
		return bld.get_tgen_by_name(name)
	except Errors.WafError:
		return None


@feature('cshlib', 'cxxshlib')
@before_method('process_source')
def static_composition_module(self):
	"""Turns a first-party shared library into a module object. apply_link uses
	the first link-task feature; cshlib/cxxshlib stay for their compile flags."""
	if not self.env.STATIC_COMPOSITION:
		return
	self.features = ['cxxmodule'] + [x for x in self.features if x != 'cxxmodule']
	self.install_path = None
	# Only modules with an interface registry (tier1's CreateInterface) get an
	# entry; tier0, for example, exports plain functions only.
	if 'tier1' not in [tg.name for tg in _private_closure(self)]:
		return
	target = os.path.basename(self.target)
	entry = self.path.find_or_declare('%s_static_module_entry.cpp' % target)
	entry.parent.mkdir()
	content = MODULE_ENTRY_TEMPLATE % {'target': target, 'entry': module_entry_name(target)}
	if not os.path.isfile(entry.abspath()) or entry.read() != content:
		entry.write(content)
	self.source = self.to_nodes(getattr(self, 'source', [])) + [entry]


@feature('cshlib', 'cxxshlib')
@after_method('process_use')
@before_method('propagate_uselib_vars')
def static_composition_private_libraries(self):
	"""The static libraries a module object links privately: first-party static
	libraries reached from its use list without passing through another module."""
	if not self.env.STATIC_COMPOSITION or not _is_module(self):
		return
	names, paths = [], []
	for tg in _private_closure(self):
		tg.post()
		link = getattr(tg, 'link_task', None)
		if isinstance(link, ccroot.stlink_task):
			names.append(os.path.basename(tg.target))
			paths.append(link.outputs[0].parent.abspath())
			self.link_task.dep_nodes.extend(link.outputs)
	self.link_task.private_stlibs = names
	self.link_task.private_stlib_paths = list(dict.fromkeys(paths))
	_drop_module_libraries(self)


def _drop_module_libraries(self):
	"""process_use added used module objects as -l libraries; only programs link them."""
	modules = set()
	for name in self.to_list(getattr(self, 'use', [])) + list(getattr(self, 'tmp_use_seen', [])):
		tg = _tgen(self.bld, name)
		if tg is not None and _is_module(tg):
			modules.add(os.path.basename(tg.target))
	if modules:
		self.env.LIB = [x for x in self.env.LIB if x not in modules]


def _module_closure(self):
	"""Module objects reached from a program's use list, dependencies first."""
	order, state = [], {}

	def visit(name):
		tg = _tgen(self.bld, name)
		if tg is None or state.get(name):
			return
		state[name] = 'visiting'
		tg.post()
		for dep in tg.to_list(getattr(tg, 'use', [])):
			visit(dep)
		if _is_module(tg):
			order.append(tg)
		state[name] = 'done'

	for name in self.to_list(getattr(self, 'use', [])):
		visit(name)
	return order


@feature('cprogram', 'cxxprogram')
@after_method('process_use')
@before_method('propagate_uselib_vars')
def static_composition_program(self):
	"""Links the closure of module objects into a product program."""
	if not self.env.STATIC_COMPOSITION or not getattr(self, 'link_task', None):
		return
	modules = _module_closure(self)
	if not modules:
		return
	_drop_module_libraries(self)
	# A module's first-party static libraries are inside its module object;
	# only the program's own direct uses may link them again.
	direct = set(self.to_list(getattr(self, 'use', [])))
	private = set()
	for name in getattr(self, 'tmp_use_seen', []):
		tg = _tgen(self.bld, name)
		if name not in direct and tg is not None and isinstance(
				getattr(tg, 'link_task', None), ccroot.stlink_task):
			private.add(os.path.basename(tg.target))
	self.env.STLIB = [x for x in self.env.STLIB if x not in private]
	objects = [tg.link_task.outputs[0] for tg in modules]
	self.link_task.inputs.extend(objects)
	uselib = self.to_list(getattr(self, 'uselib', []))
	# The system libraries of the modules and of the static libraries linked
	# into them (tier1's iconv, for example): a shared library resolved those
	# itself, a module object leaves them to the program.
	for tg in modules:
		for owner in [tg] + _private_closure(tg):
			names = owner.to_list(getattr(owner, 'uselib', []))
			names += [x for x in owner.to_list(getattr(owner, 'use', []))
				if _tgen(self.bld, x) is None]
			for name in names:
				if name not in uselib:
					uselib.append(name)
	self.uselib = uselib
	Logs.debug('static_composition: %s links %s', self.name,
		' '.join(os.path.basename(tg.target) for tg in modules))
