//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: The default indirect-light producers per platform (RFC 0011 G8):
//          r_indirect_producer auto takes the first one the map and device
//          offer. Generated by tools/quality/indirect_defaults.py from the
//          product profiles' indirect_light.default_producers; do not edit.
//
//===========================================================================//

#ifndef ENGINE_INDIRECT_LIGHT_DEFAULTS_H
#define ENGINE_INDIRECT_LIGHT_DEFAULTS_H

#if defined( ANDROID )
// quality/product_profiles/portal-android-native-vulkan.json
static const char *const kIndirectDefaultProducers[] = { "radiosity", "baked" };
#else
// quality/product_profiles/portal-linux-wayland-native-vulkan.json
static const char *const kIndirectDefaultProducers[] = { "sdf", "radiosity", "baked" };
#endif

#endif // ENGINE_INDIRECT_LIGHT_DEFAULTS_H
