#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'launcher'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('LAUNCHERONLY',1)
	conf.define('CFLAGS', conf.env.CFLAGS)
	conf.define('LDFLAGS', conf.env.LINKFLAGS)

def build(bld):
	source = [
		'../public/filesystem_init.cpp',
		'launcher.cpp',
		'reslistgenerator.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'android' and not bld.env.ANDROID_SDL3:
		source += [
			'android/main.cpp',
			'android/crashhandler.cpp'
		]

	includes = [
		'.',
		'android/libunwind',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','tier1','tier2','tier3','vstdlib','steam_api','appframework','SDL2','togl', 'UNWIND']
	if bld.env.DXVK:
		libs.remove('togl')
	libs += ['shaderapiempty', 'stdshader_dx9', 'vaudio_minimp3']
	# The composition root offers every backend this product linked through
	# -renderer. Each is built only when its SDK was configured, so guard both
	# the link and the catalog entry on the same condition.
	if bld.env.DXVK:
		libs += ['shaderapidx9']
		defines += ['LINKED_DX9_BACKEND']
	if bld.env.NATIVE_VULKAN:
		libs += ['shaderapivulkan']
		defines += ['LINKED_NATIVE_VULKAN_BACKEND']
	if bld.env.OPUS or (bld.env.DEST_OS == 'android' and not bld.env.ANDROID_SDL3):
		libs += ['vaudio_opus']
	libs += ['engine', 'inputsystem', 'materialsystem', 'datacache', 'studiorender',
	         'video_services', 'vguimatsurface', 'vgui2']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32', 'OLE32', 'SHELL32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
