#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs, Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'client'

def options(opt):
	return

games = {
	'hl2': ['client_base.vpc', 'client_hl2.vpc'],
	'hl2mp': ['client_base.vpc', 'client_hl2mp.vpc'],
	'hl1': ['client_base.vpc', 'client_hl1.vpc'],
	'episodic': ['client_base.vpc', 'client_episodic.vpc'],
	'portal': ['client_base.vpc', 'client_portal.vpc'],
	'portal2': ['client_base.vpc', 'client_portal_base.vpc', 'client_portal2.vpc'],
	'hl1mp': ['client_base.vpc', 'client_hl1mp.vpc'],
	'cstrike': ['client_base.vpc', 'client_cstrike.vpc'],
	'dod': ['client_base.vpc', 'client_dod.vpc']
}

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )
	if bld.env.GAMES == 'portal2':
		missing = [source for source in game['sources']
		           if not os.path.isfile(os.path.join(bld.path.abspath(), source))]
		if missing and os.environ.get('P2_ALLOW_INCOMPLETE') == '1':
			# Developer opt-in while the target is reconstructed; never the default.
			Logs.warn('Portal 2 client: building without %d missing sources (P2_ALLOW_INCOMPLETE=1)'
			          % len(missing))
			game['sources'] = [source for source in game['sources'] if source not in missing]
		elif missing:
			bld.fatal('Portal 2 client source is incomplete (%d selected files missing): %s'
			          % (len(missing), ', '.join(missing[:8])))

	includes = [
		'.',
		'game_controls',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../vgui2/include',
		'../../vgui2/controls',
		'../shared'
	]

	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'RT',
		'ZLIB'
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	source = [ 'in_touch.cpp' ]
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	source += game["sources"] + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	cxxflags = []
	if bld.env.GAMES == 'portal2':
		# The Portal 2 add-ons menu reads VPKs and JPEG thumbnails (client_portal2.vpc links vpklib and jpeglib).
		libs += ['vpklib', 'JPEG']
		# The imported Portal 2 sources spell some includes from the source root.
		includes += ['../..']
		# Base-game API the Portal 2 sources expect from their later base game.
		# The VPC $ForceIncludes key is not read by vpc_parser, so apply it here.
		cxxflags += ['-include', bld.path.find_node('../shared/portal2/portal2_base_compat.h').abspath()]
	defines = game["defines"]

	defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		cxxflags = cxxflags,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
