#! /usr/bin/env python
# encoding: utf-8


def options(opt):
	pass


def configure(conf):
	pass


def build(bld):
	# RFC 0010 V0: the VGUI fixture host. It composes the material system, the
	# render provider this tree links, the input system, vgui2 and
	# vguimatsurface through their typed linked factories, as the launcher
	# does, and paints the fixture screens in a staged fixture game. The
	# oracle is tools/vgui/vgui_fixture_host.py.
	if bld.env.DEDICATED or not bld.env.SDL3 or not ( bld.env.DXVK or bld.env.NATIVE_VULKAN ):
		return
	test_env = bld.env.derive()
	test_env.DEFINES = [value for value in bld.env.DEFINES
		if not value.startswith('strncpy=')]
	# vgui_controls first: the static tiers it needs must follow it on the link
	# line, and appframework would otherwise place tier1 ahead of it.
	use = ['vgui_controls', 'tier3', 'tier2', 'tier1', 'mathlib', 'appframework', 'materialsystem',
		'shaderapiempty', 'stdshader_dx9', 'inputsystem', 'filesystem_stdio', 'vgui2', 'vguimatsurface',
		'tier0',
		'vstdlib', 'SDL3']
	defines = list(test_env.DEFINES)
	if bld.env.DXVK:
		use += ['shaderapidx9']
		defines += ['LINKED_DX9_BACKEND']
	if bld.env.NATIVE_VULKAN:
		use += ['shaderapivulkan', 'render_device_vulkan', 'render_device']
		defines += ['LINKED_NATIVE_VULKAN_BACKEND']
	bld.program(
		features='cxx', env=test_env.derive(),
		source=['vgui_fixture_host.cpp', '../../public/filesystem_init.cpp',
			'../../public/vgui_controls/vgui_controls.cpp'],
		target='vgui_fixture_host', name='vgui_fixture_host',
		includes=['../../public', '../../public/tier0', '../../public/tier1', '../../common'],
		defines=defines, use=use, install_path=None)
