"Resource\OptionsSubVideo.res"
{
	"GammaButton"
	{
		"ControlName"		"Button"
		"fieldName"		"GammaButton"
		"xpos"		"254"
		"ypos"		"117"
		"wide"		"214"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"4"
		"labelText"		"#GameUI_AdjustGamma"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"Resolution"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Resolution"
		"xpos"		"36"
		"ypos"		"48"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AspectRatio"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AspectRatio"
		"xpos"		"36"
		"ypos"		"117"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HudAspectRatio"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HudAspectRatio"
		"xpos"		"36"
		"ypos"		"190"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AdvancedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"AdvancedButton"
		"xpos"		"254"
		"ypos"		"190"
		"wide"		"214"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_AdvancedEllipsis"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"BenchmarkButton"
	{
		"ControlName"		"Button"
		"fieldName"		"BenchmarkButton"
		"xpos"		"39"
		"ypos"		"230"
		"wide"		"130"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_LaunchBenchmarkVideoPanel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"ThirdPartyVideoCredits"
	{
		"ControlName"		"URLButton"
		"fieldName"		"ThirdPartyVideoCredits"
		"xpos"		"254"
		"ypos"		"270"
		"wide"		"225"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		"#GameUI_ThirdPartyTechCredits"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"DisplayModeCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DisplayModeCombo"
		"xpos"		"254"
		"ypos"		"48"
		"wide"		"214"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Gamma label"
	{
		"ControlName"		"Label"
		"fieldName"		"Gamma label"
		"xpos"		"257"
		"ypos"		"117"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gamma"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Renderer"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Renderer"
		"xpos"		"40"
		"ypos"		"52"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"36"
		"ypos"		"24"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Resolution"
		"textAlignment"		"west"
		"associate"		"Resolution"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"40"
		"ypos"		"28"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Renderer"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"254"
		"ypos"		"24"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DisplayMode"
		"textAlignment"		"west"
		"associate"		"DisplayModeCombo"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AspectRatioLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AspectRatioLabel"
		"xpos"		"36"
		"ypos"		"93"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AspectRatio"
		"textAlignment"		"west"
		"associate"		"AspectRatio"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HudAspectRatioLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HudAspectRatioLabel"
		"xpos"		"36"
		"ypos"		"166"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HUDAspectRatio"
		"textAlignment"		"west"
		"associate"		"HudAspectRatio"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HDR Label"
	{
		"ControlName"		"Label"
		"fieldName"		"HDR Label"
		"xpos"		"36"
		"ypos"		"239"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1" [!$OSX]
		"visible"		"0" [$OSX]
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HDR"
		"textAlignment"		"west"
		"associate"		"HDR"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HDR"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HDR"
		"xpos"		"36"
		"ypos"		"264"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1" [!$OSX]
		"visible"		"0" [$OSX]
		"enabled"		"1"
		"tabPosition"		"12"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"Xtooltiptext"	"#GameUI_hdr_Hint"
	}
}
