#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
#
# Compile-equivalence corpus: legacy VBSP/VVIS/VRAD lumps and PVS
# (RFC 0007 R48 "byte-identical legacy lumps and PVS vs legacy executables";
# RFC 0005 Q0 gap corpus, item 2).
#
# Four small authored maps (quality/fixtures/corpus/compile/maps, generated by
# make_maps.py next to them) are compiled vbsp -> vvis -> vrad -ldr ->
# vrad -hdr by the declared executables. Every one of the 64 lumps of the
# result is compared byte for byte with quality/fixtures/corpus/compile/
# expected.json, which the legacy executables recorded. The oracle is this
# file's own stdlib reader of the v21 header, the visibility lump (decoded to
# per-cluster PVS rows), the node tree (point -> cluster, for authored
# visibility expectations) and ColorRGBExp32 lighting; it shares no code with
# the tools.
#
# Determinism policy (the evidence is in expected.json "findings"):
#   * every tool runs with -threads 1, relative argv from the map directory, a
#     fixed environment, and under `setarch x86_64 -R` (ASLR off). Legacy VRAD
#     reads uninitialized stack memory in BuildSupersampleFaceLights (valgrind:
#     "conditional jump depends on uninitialised value ... stack allocation"),
#     so with ASLR or more than one worker its supersampling decisions, and
#     LIGHTING/LIGHTING_HDR/leaf-ambient bytes, vary run to run. With
#     supersampling off (-noextra) the output is identical across ASLR and
#     1/4/32 threads. The policy fixes the execution rather than hiding bytes.
#   * DISPINFO (lump 26) carries bytes VBSP never writes: CDispSubNeighbor
#     fields after an invalid (0xFFFF) neighbor index, CDispCornerNeighbors
#     slots at or beyond m_nNeighbors, and struct padding. Those, and only
#     those, bytes are masked; the rest of the lump is compared exactly.
#   * the suite compiles every map twice and first requires the two results to
#     agree (a nondeterministic host fails `<map>.deterministic`, not the gate).
#
# Modes:
#   compile_equivalence.py [--tools DIR] [--maps a,b] [--seed-fault F]
#       The suite. Seeded faults (negative rows): `lump-byte` flips one
#       LIGHTING byte of box_light; `vis-bit` toggles one PVS bit of
#       three_rooms (re-encoded, so the decoded-PVS comparison names it first);
#       `vrad-noextra` runs VRAD without supersampling, a tool-behaviour change
#       that must surface as a LIGHTING divergence.
#   compile_equivalence.py record --tools DIR [--reference-tools DIR ...]
#       [--study-runs N] [--gdb-probe]
#       Rewrites expected.json and fixture.json from DIR's executables, runs
#       the determinism study, and compares each reference build (for example
#       the pre-fix `ad7120f3^` build) with DIR under the policy, with
#       supersampling off, and as ASLR outcome sets.
#
# Python 3 standard library only.
#
# ============================================================================

import argparse
import collections
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

from conformance_result import Checks  # noqa: E402
from corpus import provenance  # noqa: E402

ROOT = provenance.ROOT
FIXTURE = os.path.join(ROOT, "quality/fixtures/corpus/compile")
EXPECTED = os.path.join(FIXTURE, "expected.json")
FIXTURE_JSON = os.path.join(FIXTURE, "fixture.json")
SUITE = "corpus.compile.legacy-lumps"
SCHEMA = "corpus-compile-equivalence/v1"
VERSION = 1
DEFAULT_TOOLS = "build-corpus-tools/install"
TOOLS = ("vbsp", "vvis", "vrad")

MAPS = collections.OrderedDict([
    ("box_light", "sealed box room, one point light: baseline geometry, vis and direct light"),
    ("disp_occluder", "power-3 displacement hump between a point light and a floor of two sewn "
                      "power-2 displacements: displacement geometry, neighbors, disp lightmaps, "
                      "and shadow rays that cross displacement triangles"),
    ("three_rooms", "three rooms on a dogleg corridor with func_detail crates: real VVIS flow, "
                    "rooms A and C mutually hidden"),
    ("sky_spot", "light_environment through a skybox chimney plus a light_spot: sun, sky "
                 "ambient and cone falloff"),
])

# Authored visibility facts (from make_maps.VIS_GRID; independent of any tool):
# (map, label, point_a, point_b, visible)
PVS_EXPECTATIONS = [
    ("three_rooms", "room-a-sees-room-b", (320, 1216, 128), (1216, 1088, 128), True),
    ("three_rooms", "room-a-hides-room-c", (320, 1216, 128), (704, 320, 128), False),
    ("three_rooms", "room-c-hides-room-a", (704, 320, 128), (320, 1216, 128), False),
    ("three_rooms", "room-c-sees-corridor", (704, 320, 128), (832, 576, 128), True),
]

ENV = {"PATH": "/usr/bin:/bin", "LC_ALL": "C", "HOME": "/nonexistent", "TZ": "UTC"}
NOASLR = ["setarch", "x86_64", "-R"]
TOOL_TIMEOUT = 300

LUMP_NAMES = [
    "ENTITIES", "PLANES", "TEXDATA", "VERTEXES", "VISIBILITY", "NODES", "TEXINFO", "FACES",
    "LIGHTING", "OCCLUSION", "LEAFS", "FACEIDS", "EDGES", "SURFEDGES", "MODELS", "WORLDLIGHTS",
    "LEAFFACES", "LEAFBRUSHES", "BRUSHES", "BRUSHSIDES", "AREAS", "AREAPORTALS", "PORTALS",
    "CLUSTERS", "PORTALVERTS", "CLUSTERPORTALS", "DISPINFO", "ORIGINALFACES", "PHYSDISP",
    "PHYSCOLLIDE", "VERTNORMALS", "VERTNORMALINDICES", "DISP_LIGHTMAP_ALPHAS", "DISP_VERTS",
    "DISP_LIGHTMAP_SAMPLE_POSITIONS", "GAME_LUMP", "LEAFWATERDATA", "PRIMITIVES", "PRIMVERTS",
    "PRIMINDICES", "PAKFILE", "CLIPPORTALVERTS", "CUBEMAPS", "TEXDATA_STRING_DATA",
    "TEXDATA_STRING_TABLE", "OVERLAYS", "LEAFMINDISTTOWATER", "FACE_MACRO_TEXTURE_INFO",
    "DISP_TRIS", "PHYSCOLLIDESURFACE", "WATEROVERLAYS", "LEAF_AMBIENT_INDEX_HDR",
    "LEAF_AMBIENT_INDEX", "LIGHTING_HDR", "WORLDLIGHTS_HDR", "LEAF_AMBIENT_LIGHTING_HDR",
    "LEAF_AMBIENT_LIGHTING", "XZIPPAKFILE", "FACES_HDR", "MAP_FLAGS", "OVERLAY_FADES",
    "UNUSED61", "UNUSED62", "UNUSED63",
]
L_VISIBILITY, L_LIGHTING, L_DISPINFO, L_LIGHTING_HDR = 4, 8, 26, 53
L_PLANES, L_NODES, L_LEAFS, L_MODELS, L_FACES, L_TEXINFO, L_FACES_HDR = 1, 5, 10, 14, 7, 6, 58
LIGHT_LUMPS = (8, 51, 52, 53, 55, 56)
HEADER_BYTES = 8 + 16 * 64 + 4


def sha(data):
    return hashlib.sha256(data).hexdigest()


def lump_label(index):
    return "lump.%d.%s" % (index, LUMP_NAMES[index])


# ---------------------------------------------------------------------------
# Independent v21 reader
# ---------------------------------------------------------------------------

def read_bsp(data):
    """Header and the 64 lumps of a legacy VBSP; raises ValueError when malformed."""
    if len(data) < HEADER_BYTES or data[:4] != b"VBSP":
        raise ValueError("not a VBSP file")
    version = struct.unpack_from("<i", data, 4)[0]
    lumps = []
    for i in range(64):
        ofs, length, lversion, fourcc = struct.unpack_from("<iiii", data, 8 + 16 * i)
        if length < 0 or (length and (ofs < HEADER_BYTES or ofs + length > len(data))):
            raise ValueError("lump %d is out of bounds" % i)
        lumps.append({"data": data[ofs:ofs + length], "version": lversion, "fourcc": fourcc})
    revision = struct.unpack_from("<i", data, 8 + 16 * 64)[0]
    return {"version": version, "revision": revision, "lumps": lumps}


def dispinfo_mask(lump):
    """1 for every DISPINFO byte VBSP defines, 0 for the bytes it leaves unset
    (ddispinfo_t, public/bspfile.h: 176 bytes per record)."""
    record = 176
    if len(lump) % record:
        raise ValueError("DISPINFO is not a whole number of 176-byte records")
    mask = bytearray(b"\x01" * len(lump))
    for base in range(0, len(lump), record):
        mask[base + 38:base + 40] = b"\0\0"                 # padding after m_iMapFace
        for sub in range(8):                                # m_EdgeNeighbors[4].m_SubNeighbors[2]
            at = base + 48 + 6 * sub
            mask[at + 5] = 0                                # padding
            if struct.unpack_from("<H", lump, at)[0] == 0xFFFF:
                mask[at + 2:at + 5] = b"\0\0\0"             # orientation, span, neighbor span
        for corner in range(4):                             # m_CornerNeighbors[4]
            at = base + 96 + 10 * corner
            count = lump[at + 8]
            if count > 4:
                raise ValueError("corner neighbor count %d exceeds 4" % count)
            for slot in range(count, 4):
                mask[at + 2 * slot:at + 2 * slot + 2] = b"\0\0"
            mask[at + 9] = 0                                # padding
    return bytes(mask)


def masked(lump, mask):
    return bytes(b & (0xFF if m else 0) for b, m in zip(lump, mask))


def lump_digest(index, data):
    """(sha256 of the compared bytes, number of masked bytes)."""
    if index == L_DISPINFO and data:
        mask = dispinfo_mask(data)
        return sha(masked(data, mask) + mask), mask.count(0)
    return sha(data), 0


def decode_pvs(lump):
    """Per-cluster sorted lists of visible clusters from the RLE visibility lump."""
    if len(lump) < 4:
        return None
    count = struct.unpack_from("<i", lump, 0)[0]
    if count <= 0 or 4 + 8 * count > len(lump):
        raise ValueError("visibility header is malformed")
    width = (count + 7) // 8
    rows = []
    for cluster in range(count):
        offset = struct.unpack_from("<i", lump, 4 + 8 * cluster)[0]
        row = bytearray()
        while len(row) < width:
            if offset >= len(lump):
                raise ValueError("PVS row %d runs past the lump" % cluster)
            if lump[offset]:
                row.append(lump[offset])
                offset += 1
            else:
                if offset + 1 >= len(lump):
                    raise ValueError("PVS row %d is truncated" % cluster)
                row.extend(b"\0" * lump[offset + 1])
                offset += 2
        rows.append([c for c in range(count) if row[c >> 3] & (1 << (c & 7))])
    return rows


def encode_pvs(rows, pas_lump):
    """Re-encode PVS rows (standard zero-run RLE) keeping the PAS rows of
    `pas_lump`; used only to seed a fault."""
    count = len(rows)
    width = (count + 7) // 8

    def rle(bits):
        out, i = bytearray(), 0
        while i < width:
            if bits[i]:
                out.append(bits[i])
                i += 1
                continue
            run = 0
            while i < width and not bits[i] and run < 255:
                run += 1
                i += 1
            out += bytes((0, run))
        return bytes(out)

    body = bytearray()
    offsets = []
    for c, visible in enumerate(rows):
        bits = bytearray(width)
        for v in visible:
            bits[v >> 3] |= 1 << (v & 7)
        pvs = rle(bits)
        pas_ofs = struct.unpack_from("<i", pas_lump, 8 + 8 * c)[0]
        pas = pas_lump[pas_ofs:]
        pas_len, got = 0, 0
        while got < width:                       # length of the original PAS row
            if pas[pas_len]:
                got += 1
                pas_len += 1
            else:
                got += pas[pas_len + 1]
                pas_len += 2
        offsets.append((len(body), len(body) + len(pvs)))
        body += pvs + pas[:pas_len]
    head = 4 + 8 * count
    out = bytearray(struct.pack("<i", count))
    for a, b in offsets:
        out += struct.pack("<ii", head + a, head + b)
    return bytes(out + body)


def point_cluster(bsp, point):
    """The cluster of the leaf containing `point`, walking model 0's node tree."""
    planes = bsp["lumps"][L_PLANES]["data"]
    nodes = bsp["lumps"][L_NODES]["data"]
    leafs = bsp["lumps"][L_LEAFS]["data"]
    models = bsp["lumps"][L_MODELS]["data"]
    node = struct.unpack_from("<i", models, 36)[0]
    for _ in range(4096):
        if node < 0:
            leaf = -1 - node
            if (leaf + 1) * 32 > len(leafs):
                raise ValueError("leaf index out of range")
            return struct.unpack_from("<h", leafs, leaf * 32 + 4)[0]
        if (node + 1) * 32 > len(nodes):
            raise ValueError("node index out of range")
        planenum, front, back = struct.unpack_from("<iii", nodes, node * 32)
        nx, ny, nz, dist = struct.unpack_from("<4f", planes, planenum * 20)
        side = nx * point[0] + ny * point[1] + nz * point[2] - dist
        node = front if side >= 0 else back
    raise ValueError("node tree does not terminate")


def rgbe(lump, offset):
    r, g, b, e = struct.unpack_from("<BBBb", lump, offset)
    scale = 2.0 ** e
    return (r * scale, g * scale, b * scale)


def lighting_diff(a, b):
    """How two ColorRGBExp32 lighting lumps differ."""
    if len(a) != len(b):
        return {"samples": None, "sizes": [len(a), len(b)]}
    differ, max_abs, max_rel = 0, 0.0, 0.0
    for i in range(0, len(a), 4):
        if a[i:i + 4] == b[i:i + 4]:
            continue
        differ += 1
        x, y = rgbe(a, i), rgbe(b, i)
        d = max(abs(p - q) for p, q in zip(x, y))
        top = max(max(x), max(y))
        max_abs = max(max_abs, d)
        max_rel = max(max_rel, d / top if top else 0.0)
    return {"samples": len(a) // 4, "differ": differ, "max_abs": round(max_abs, 6),
            "max_rel": round(max_rel, 6)}


def lighting_summary(lump):
    return {"bytes": len(lump), "samples": len(lump) // 4,
            "nonzero_samples": sum(1 for i in range(0, len(lump), 4) if lump[i:i + 3] != b"\0\0\0"),
            "sha256": sha(lump)}


# ---------------------------------------------------------------------------
# Running the legacy tools
# ---------------------------------------------------------------------------

def tool_paths(tools_dir):
    return {name: os.path.join(tools_dir, name) for name in TOOLS}


def stage_argvs(tools_dir, name, threads=("-threads", "1"), extra=()):
    t = tool_paths(tools_dir)
    return [
        ("vbsp", [t["vbsp"]] + list(threads) + ["-game", "game", name + ".vmf"]),
        ("vvis", [t["vvis"]] + list(threads) + ["-game", "game", name + ".bsp"]),
        ("vrad-ldr", [t["vrad"]] + list(threads) + list(extra) + ["-ldr", "-game", "game",
                                                                  name + ".bsp"]),
        ("vrad-hdr", [t["vrad"]] + list(threads) + list(extra) + ["-hdr", "-game", "game",
                                                                  name + ".bsp"]),
    ]


def prepare(work, name):
    if os.path.exists(work):
        shutil.rmtree(work)
    os.makedirs(work)
    shutil.copytree(os.path.join(FIXTURE, "game"), os.path.join(work, "game"))
    shutil.copy2(os.path.join(FIXTURE, "maps", name + ".vmf"), os.path.join(work, name + ".vmf"))


def run_tool(argv, work, log, noaslr=True):
    full = (NOASLR if noaslr else []) + argv
    try:
        result = subprocess.run(full, cwd=work, env=ENV, capture_output=True, text=True,
                                errors="replace", timeout=TOOL_TIMEOUT, check=False)
        code, out = result.returncode, result.stdout + result.stderr
    except subprocess.TimeoutExpired as error:
        code, out = "timeout", str(error)
    except OSError as error:
        code, out = "oserror", str(error)
    with open(log, "a", encoding="utf-8") as stream:
        stream.write("$ %s\n%s\nexit %s\n\n" % (" ".join(full), out, code))
    return code


def compile_map(tools_dir, name, work, noaslr=True, threads=("-threads", "1"), extra=()):
    """Compile one fixture under the policy. Returns (bsp bytes or None,
    failed stage or None, per-stage lump digests)."""
    prepare(work, name)
    log = os.path.join(work, "tools.log")
    bsp_path = os.path.join(work, name + ".bsp")
    stages = {}
    for stage, argv in stage_argvs(tools_dir, name, threads, extra):
        code = run_tool(argv, work, log, noaslr)
        if code != 0 or not os.path.isfile(bsp_path):
            return None, "%s exit %s" % (stage, code), stages
        with open(bsp_path, "rb") as stream:
            bsp = read_bsp(stream.read())
        stages[stage] = {str(i): lump_digest(i, l["data"])[0]
                         for i, l in enumerate(bsp["lumps"]) if l["data"]}
    with open(bsp_path, "rb") as stream:
        return stream.read(), None, stages


def rerun_vrad(tools_dir, name, work, pre_vrad, noaslr, threads, extra=()):
    """VRAD only (-ldr then -hdr) on a fixed VVIS output."""
    bsp_path = os.path.join(work, name + ".bsp")
    with open(bsp_path, "wb") as stream:
        stream.write(pre_vrad)
    log = os.path.join(work, "study.log")
    for stage, argv in stage_argvs(tools_dir, name, threads, extra)[2:]:
        code = run_tool(argv, work, log, noaslr)
        if code != 0:
            raise RuntimeError("%s %s exit %s (see %s)" % (name, stage, code, log))
    with open(bsp_path, "rb") as stream:
        return stream.read()


# ---------------------------------------------------------------------------
# Build identity (which source revision and compiler produced an executable)
# ---------------------------------------------------------------------------

def git(cwd, *args):
    try:
        return subprocess.run(["git", "-C", cwd] + list(args), capture_output=True, text=True,
                              check=False, timeout=60).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None


def build_identity(tools_dir):
    tools_dir = os.path.abspath(tools_dir)
    identity = {"tools_dir": tools_dir,
                "executables": {name: {"path": path,
                                       "sha256": provenance.file_sha256(path)
                                       if os.path.isfile(path) else None}
                                for name, path in tool_paths(tools_dir).items()}}
    build_dir = os.path.dirname(tools_dir)
    cache = os.path.join(build_dir, "c4che", "_cache.py")
    if os.path.isfile(cache):
        text = open(cache, encoding="utf-8", errors="replace").read()

        def value(key):
            m = re.search(r"^%s = (.*)$" % re.escape(key), text, re.MULTILINE)
            return m.group(1) if m else None

        cxx = value("CXX")
        commit = re.search(r"GIT_COMMIT_HASH=\\?\"([^\"\\]*)", text)
        identity["build_dir"] = build_dir
        identity["cxx"] = cxx
        identity["cxxflags"] = value("CXXFLAGS")
        identity["git_commit_hash_define"] = commit.group(1) if commit else None
        try:
            compiler = json.loads(cxx.replace("'", '"'))[0] if cxx else None
        except ValueError:
            compiler = None
        identity["compiler_version"] = provenance.tool_version([compiler, "--version"]) \
            if compiler else None
        worktree = os.path.dirname(build_dir)
        identity["worktree"] = worktree
        identity["source_revision"] = git(worktree, "rev-parse", "HEAD")
        # Only the build inputs matter: Python/fixture edits cannot change a binary.
        status = git(worktree, "status", "--porcelain", "--untracked-files=no", "--", ".",
                     ":(exclude)tools/quality", ":(exclude)quality")
        # A dirty path the build compiled nothing from (for example a submodule
        # the tools product does not use) cannot have changed the executables.
        identity["tool_sources_dirty"] = [
            {"status": line[:2].strip(), "path": line[3:],
             "compiled_by_this_build": os.path.isdir(os.path.join(build_dir, line[3:]))}
            for line in sorted(status.splitlines())] if status else []
        identity["executables_mtime"] = {
            name: time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime(
                os.path.getmtime(path))) for name, path in tool_paths(tools_dir).items()
            if os.path.isfile(path)}
    return identity


# ---------------------------------------------------------------------------
# Suite
# ---------------------------------------------------------------------------

def compared(entry):
    """The fields of a lump-table entry the gate compares (raw_sha256 of a
    masked lump is recorded for information only)."""
    return {k: v for k, v in entry.items() if k != "raw_sha256"}


def lump_table(bsp):
    table = {}
    for i, lump in enumerate(bsp["lumps"]):
        digest, masked_bytes = lump_digest(i, lump["data"])
        entry = {"name": LUMP_NAMES[i], "size": len(lump["data"]), "version": lump["version"],
                 "fourcc": lump["fourcc"], "sha256": digest}
        if masked_bytes:
            entry["masked_bytes"] = masked_bytes
            entry["raw_sha256"] = sha(lump["data"])
        table[str(i)] = entry
    return table


def seed_fault(fault, name, bsp):
    """Apply a seeded fault to a parsed candidate; returns a description or None."""
    if fault == "lump-byte" and name == "box_light":
        lump = bytearray(bsp["lumps"][L_LIGHTING]["data"])
        at = (len(lump) // 8) * 4                  # the red byte of a mid-lump sample
        lump[at] ^= 0x01
        bsp["lumps"][L_LIGHTING]["data"] = bytes(lump)
        return "flipped bit 0 of LIGHTING byte %d" % at
    if fault == "vis-bit" and name == "three_rooms":
        vis = bsp["lumps"][L_VISIBILITY]["data"]
        rows = decode_pvs(vis)
        a = point_cluster(bsp, PVS_EXPECTATIONS[1][2])
        c = point_cluster(bsp, PVS_EXPECTATIONS[1][3])
        rows[a] = sorted(set(rows[a]) ^ {c})
        bsp["lumps"][L_VISIBILITY]["data"] = encode_pvs(rows, vis)
        return "toggled PVS bit cluster %d -> %d" % (a, c)
    return None


def check_map(checks, name, spec, tools_dir, out, fault):
    runs = []
    for attempt in (0, 1):
        # Seeded tool regression: VRAD without supersampling (-noextra).
        extra = ("-noextra",) if fault == "vrad-noextra" else ()
        data, failed, _ = compile_map(tools_dir, name, os.path.join(out, name, "run%d" % attempt),
                                      extra=extra)
        if not checks.check(failed is None, "%s.compile.run%d" % (name, attempt),
                            "%s (log: %s)" % (failed, os.path.join(out, name, "run%d" % attempt,
                                                                   "tools.log"))):
            return
        runs.append(read_bsp(data))
    first, second = lump_table(runs[0]), lump_table(runs[1])
    unstable = [lump_label(int(i)) for i in first if compared(first[i]) != compared(second[i])]
    checks.check(not unstable, "%s.deterministic" % name,
                 "two compiles under the policy differ in " + ", ".join(unstable))

    bsp = runs[0]
    seeded = seed_fault(fault, name, bsp)
    if seeded:
        print("SEEDED %s: %s" % (name, seeded))

    checks.equal(bsp["version"], spec["header"]["version"], "%s.header.version" % name)
    checks.equal(bsp["revision"], spec["header"]["revision"], "%s.header.revision" % name)

    # PVS first: a visibility defect is named by the decoded comparison.
    rows = decode_pvs(bsp["lumps"][L_VISIBILITY]["data"])
    expected_rows = spec["pvs"]["rows"]
    if checks.equal(len(rows or []), spec["pvs"]["clusters"], "%s.pvs.clusters" % name):
        for c, row in enumerate(rows):
            checks.check(row == expected_rows[c], "%s.pvs.cluster.%d" % (name, c),
                         "sees %s, legacy recorded %s" % (row, expected_rows[c]))
    for map_name, label, pa, pb, visible in PVS_EXPECTATIONS:
        if map_name != name:
            continue
        a, b = point_cluster(bsp, pa), point_cluster(bsp, pb)
        seen = rows is not None and 0 <= a < len(rows) and b in rows[a]
        checks.check(seen == visible, "%s.pvs.authored.%s" % (name, label),
                     "cluster %d %s cluster %d" % (a, "sees" if seen else "does not see", b))

    table = lump_table(bsp)
    for i in range(64):
        want, got = spec["lumps"][str(i)], table[str(i)]
        label = "%s.%s" % (name, lump_label(i))
        if compared(got) == compared(want):
            checks.check(True, label)
            continue
        detail = "size %d/%d version %d/%d sha256 %s.. legacy %s.." % (
            got["size"], want["size"], got["version"], want["version"],
            got["sha256"][:12], want["sha256"][:12])
        checks.check(False, label, detail)

    for key, index in (("ldr", L_LIGHTING), ("hdr", L_LIGHTING_HDR)):
        summary = lighting_summary(bsp["lumps"][index]["data"])
        checks.check(summary["nonzero_samples"] > 0, "%s.lighting.%s.nonzero" % (name, key),
                     "no lit samples")


def load_expected(path):
    with open(path, encoding="utf-8") as stream:
        data = json.load(stream)
    if data.get("schema") != SCHEMA or data.get("version") != VERSION:
        raise ValueError("%s is not %s version %d" % (path, SCHEMA, VERSION))
    return data


def suite(args):
    checks = Checks()
    out = args.out or os.environ.get("CONFORMANCE_OUT") or tempfile.mkdtemp(prefix="compile-eq-")
    os.makedirs(out, exist_ok=True)
    tools_dir = os.path.abspath(os.path.join(ROOT, args.tools))
    expected = load_expected(args.expected)
    maps = args.maps.split(",") if args.maps else list(MAPS)

    identity = build_identity(tools_dir)
    provenance.emit(provenance.collect(
        SUITE,
        tools={"setarch": provenance.tool_version(["setarch", "--version"]),
               "candidate": identity,
               "expected_recorded_by": expected["builds"][expected["primary_build"]]},
        inputs=dict([("expected", args.expected)] +
                    [(m, os.path.join(FIXTURE, "maps", m + ".vmf")) for m in maps]),
        extra={"policy": expected["policy"], "seed_fault": args.seed_fault}), out)

    for name, path in tool_paths(tools_dir).items():
        checks.check(os.path.isfile(path) and os.access(path, os.X_OK),
                     "tools.%s.present" % name, path)
    if checks.failures:
        return checks.report()

    # The fixture maps are the generator's output and the ones legacy compiled.
    sys.path.insert(0, FIXTURE)
    sys.dont_write_bytecode = True          # keep the fixture directory clean
    import make_maps  # noqa: E402
    for make in make_maps.MAKERS:
        m = make()
        if m.name not in maps:
            continue
        path = os.path.join(FIXTURE, "maps", m.name + ".vmf")
        text = open(path, encoding="utf-8").read()
        checks.check(text == m.text(), "%s.vmf.generated" % m.name,
                     "differs from make_maps.py output")
        checks.equal(sha(text.encode("utf-8")), expected["maps"][m.name]["vmf_sha256"],
                     "%s.vmf.recorded" % m.name)

    for name in maps:
        check_map(checks, name, expected["maps"][name], tools_dir, out, args.seed_fault)
    return checks.report()


# ---------------------------------------------------------------------------
# Recording and the determinism / cross-build study
# ---------------------------------------------------------------------------

def light_key(bsp):
    return tuple(sha(bsp["lumps"][i]["data"])[:16] for i in LIGHT_LUMPS)


def study_build(tools_dir, reference, runs, scratch):
    """Outcome counts of VRAD alone on the policy VVIS output of `reference`."""
    result = {}
    for name in MAPS:
        work = os.path.join(scratch, name)
        prepare(work, name)
        pre_vrad = reference[name]["pre_vrad"]
        policy = reference[name]["bsp"]
        policy_key = light_key(policy)
        conditions = [
            ("policy", True, ("-threads", "1"), ()),
            ("aslr-threads-1", False, ("-threads", "1"), ()),
            ("aslr-default-threads", False, (), ()),
            ("noaslr-default-threads", True, (), ()),
            ("noextra-aslr-threads-1", False, ("-threads", "1"), ("-noextra",)),
            ("noextra-aslr-threads-4", False, ("-threads", "4"), ("-noextra",)),
            ("noextra-aslr-default-threads", False, (), ("-noextra",)),
        ]
        per = {}
        noextra_keys = set()
        for label, noaslr, threads, extra in conditions:
            outcomes = collections.Counter()
            worst = {"LIGHTING": None, "LIGHTING_HDR": None}
            varying = set()
            for _ in range(runs):
                bsp = read_bsp(rerun_vrad(tools_dir, name, work, pre_vrad, noaslr, threads,
                                          extra))
                key = light_key(bsp)
                outcomes[key] += 1
                if extra:
                    noextra_keys.add(key)
                    continue
                for i in range(64):
                    if bsp["lumps"][i]["data"] != policy["lumps"][i]["data"]:
                        varying.add(LUMP_NAMES[i])
                for index, lname in ((L_LIGHTING, "LIGHTING"), (L_LIGHTING_HDR, "LIGHTING_HDR")):
                    diff = lighting_diff(policy["lumps"][index]["data"], bsp["lumps"][index]["data"])
                    if diff.get("differ") and (worst[lname] is None or
                                               diff["differ"] > worst[lname]["differ"]):
                        worst[lname] = diff
            per[label] = {"runs": runs, "distinct_outcomes": len(outcomes),
                          "runs_matching_policy": outcomes.get(policy_key, 0),
                          # Outcome = the six lighting lumps' digests, joined.
                          "outcomes": {sha("/".join(k).encode())[:16]: n
                                       for k, n in sorted(outcomes.items())}}
            if not extra:
                per[label]["lumps_differing_from_policy"] = sorted(varying)
                per[label]["largest_lighting_difference"] = worst
        per["noextra_distinct_across_aslr_and_threads"] = len(noextra_keys)
        result[name] = per
    return result


def record_build(tools_dir, scratch, repeats=3):
    """Policy compiles of every map, `repeats` times; returns per-map records."""
    maps = {}
    for name in MAPS:
        raws = []
        for attempt in range(repeats):
            work = os.path.join(scratch, name, "policy%d" % attempt)
            data, failed, stages = compile_map(tools_dir, name, work)
            if failed:
                raise RuntimeError("%s: %s (see %s)" % (name, failed,
                                                        os.path.join(work, "tools.log")))
            raws.append((data, stages))
        # The VVIS output (VRAD input) of the first attempt, for the study.
        work = os.path.join(scratch, name, "policy0")
        prepare(work + "-vis", name)
        log = os.path.join(work + "-vis", "tools.log")
        for stage, argv in stage_argvs(tools_dir, name)[:2]:
            if run_tool(argv, work + "-vis", log) != 0:
                raise RuntimeError("%s %s failed" % (name, stage))
        with open(os.path.join(work + "-vis", name + ".bsp"), "rb") as stream:
            pre_vrad = stream.read()
        bsps = [read_bsp(d) for d, _ in raws]
        tables = [lump_table(b) for b in bsps]
        dispinfo_raw = sorted({sha(b["lumps"][L_DISPINFO]["data"]) for b in bsps})
        maps[name] = {"bsp": bsps[0], "tables": tables, "stages": raws[0][1],
                      "pre_vrad": pre_vrad, "dispinfo_raw_variants": dispinfo_raw}
    return maps


def dispinfo_variance(records):
    """Raw DISPINFO bytes that differ between records, and whether every one
    of them is masked."""
    lumps = [r["bsp"]["lumps"][L_DISPINFO]["data"] for r in records]
    lumps = [l for l in lumps if l]
    if len(lumps) < 2:
        return None
    mask = dispinfo_mask(lumps[0])
    offsets = sorted({i for l in lumps[1:] for i in range(len(l)) if l[i] != lumps[0][i]})
    return {"differing_raw_bytes": len(offsets),
            "all_within_mask": all(mask[i] == 0 for i in offsets),
            "masked_bytes": mask.count(0), "lump_bytes": len(lumps[0])}


def gdb_probe(tools_dir, scratch):
    """Hit counts of VRAD's displacement ray functions on disp_occluder."""
    work = os.path.join(scratch, "gdb")
    prepare(work, "disp_occluder")
    log = os.path.join(work, "tools.log")
    for stage, argv in stage_argvs(tools_dir, "disp_occluder")[:2]:
        if run_tool(argv, work, log) != 0:
            raise RuntimeError("gdb probe: %s failed" % stage)
    commands = ["set debuginfod enabled off", "set pagination off",
                "set breakpoint pending on", "rbreak ^CVRadDispMgr::ClipRayToDisp",
                "rbreak ^CVRadDispMgr::DispRay_Enumerate",
                "rbreak ^CBSPDispRayEnumerator::", "rbreak ^CBSPDispRayDistanceEnumerator::",
                "rbreak ^CVRadDispMgr::AddPolysForRayTrace"]
    commands += ["ignore %d 1000000000" % n for n in range(1, 11)]
    commands += ["run", "info breakpoints"]
    script = os.path.join(work, "gdb.cmds")
    with open(script, "w", encoding="utf-8") as stream:
        stream.write("\n".join(commands) + "\n")
    argv = ["gdb", "-q", "-batch", "-x", script, "--args",
            os.path.join(tools_dir, "vrad"), "-threads", "1", "-ldr", "-game", "game",
            "disp_occluder.bsp"]
    result = subprocess.run(argv, cwd=work, env=ENV, capture_output=True, text=True,
                            errors="replace", timeout=3600, check=False)
    hits, current = {}, None
    for line in result.stdout.splitlines():
        m = re.match(r"^\d+\s+breakpoint\s+keep\s+\w+\s+0x[0-9a-f]+\s+<(.*)>$", line.strip())
        if m:
            current = m.group(1)
            hits[current] = 0
            continue
        m = re.search(r"breakpoint already hit (\d+) time", line)
        if m and current:
            hits[current] = int(m.group(1))
    return {"command": " ".join(argv), "cwd_map": "disp_occluder (policy vbsp/vvis output)",
            "exit_code": result.returncode, "hits": hits}


def record(args):
    tools_dir = os.path.abspath(args.tools)
    scratch = args.out or tempfile.mkdtemp(prefix="compile-eq-record-")
    builds = {args.label: build_identity(tools_dir)}
    primary = record_build(tools_dir, os.path.join(scratch, "primary"))

    findings = {"determinism": {}, "cross_build": {}}
    for name, rec in primary.items():
        if any({i: compared(e) for i, e in t.items()} !=
               {i: compared(e) for i, e in rec["tables"][0].items()} for t in rec["tables"][1:]):
            raise RuntimeError("%s is not deterministic under the policy" % name)
        # Raw DISPINFO across the policy repeats (their paths differ, so the
        # garbage VBSP leaves in unset bytes can differ too).
        findings["determinism"].setdefault("dispinfo_policy_repeats", {})[name] = {
            "policy_repeats": len(rec["tables"]),
            "distinct_raw_sha256": len({t[str(L_DISPINFO)].get("raw_sha256") for t in
                                        rec["tables"]} - {None}),
        }

    study_runs = args.study_runs
    study = None
    if study_runs:
        study = findings["determinism"]["study"] = study_build(
            tools_dir, primary, study_runs, os.path.join(scratch, "study-primary"))

    for ref in args.reference_tools or []:
        ref_dir = os.path.abspath(ref)
        label = args.reference_label[len(findings["cross_build"])] \
            if args.reference_label and len(args.reference_label) > len(findings["cross_build"]) \
            else os.path.basename(os.path.dirname(os.path.dirname(ref_dir)))
        builds[label] = build_identity(ref_dir)
        other = record_build(ref_dir, os.path.join(scratch, "ref-" + label))
        cmp = {}
        for name in MAPS:
            mine, theirs = primary[name]["tables"][0], other[name]["tables"][0]
            differing = [lump_label(int(i)) for i in mine
                         if compared(mine[i]) != compared(theirs[i])]
            raw = [lump_label(int(i)) for i in mine
                   if mine[i].get("raw_sha256", mine[i]["sha256"]) !=
                   theirs[i].get("raw_sha256", theirs[i]["sha256"])]
            cmp[name] = {"policy_lumps_differing": differing,
                         "policy_raw_lumps_differing": raw,
                         "dispinfo_raw_variance": dispinfo_variance([primary[name], other[name]]),
                         "stages_identical": primary[name]["stages"] == other[name]["stages"]}
        entry = {"compared_with": args.label, "maps": cmp}
        if study_runs:
            # VRAD alone, on the *primary* build's VVIS output, so only VRAD differs.
            ref_study = study_build(ref_dir, primary, study_runs,
                                    os.path.join(scratch, "study-" + label))
            entry["vrad_study_on_primary_vvis_output"] = ref_study
            entry["noextra_identical"] = {}
            # Same condition, both builds: outcomes only one build produced.
            entry["outcome_sets"] = {
                name: {cond: {"only_" + args.label: sorted(
                                  set(study[name][cond]["outcomes"]) -
                                  set(ref_study[name][cond]["outcomes"])),
                              "only_" + label: sorted(
                                  set(ref_study[name][cond]["outcomes"]) -
                                  set(study[name][cond]["outcomes"])),
                              "shared": len(set(study[name][cond]["outcomes"]) &
                                            set(ref_study[name][cond]["outcomes"]))}
                       for cond in study[name] if isinstance(study[name][cond], dict)}
                for name in MAPS}
            for name in MAPS:
                work = os.path.join(scratch, "noextra-" + label, name)
                prepare(work, name)
                a = light_key(read_bsp(rerun_vrad(tools_dir, name, work,
                                                  primary[name]["pre_vrad"], False,
                                                  ("-threads", "1"), ("-noextra",))))
                b = light_key(read_bsp(rerun_vrad(ref_dir, name, work,
                                                  primary[name]["pre_vrad"], False,
                                                  ("-threads", "1"), ("-noextra",))))
                entry["noextra_identical"][name] = a == b
        if args.gdb_probe:
            entry["gdb_probe"] = gdb_probe(ref_dir, os.path.join(scratch, "gdb-" + label))
        findings["cross_build"][label] = entry
    if args.gdb_probe:
        findings["gdb_probe_" + args.label] = gdb_probe(tools_dir,
                                                        os.path.join(scratch, "gdb-primary"))

    command = [sys.executable, os.path.relpath(os.path.abspath(__file__), ROOT)] + sys.argv[1:]
    block = provenance.collect(
        SUITE + ".record", tools={"setarch": provenance.tool_version(["setarch", "--version"]),
                                  "gdb": provenance.tool_version(["gdb", "--version"]),
                                  "builds": builds},
        inputs=dict([(m, os.path.join(FIXTURE, "maps", m + ".vmf")) for m in MAPS] +
                    [("make_maps", os.path.join(FIXTURE, "make_maps.py"))]),
        command=command)

    maps = collections.OrderedDict()
    for name, rec in primary.items():
        bsp = rec["bsp"]
        vis = bsp["lumps"][L_VISIBILITY]["data"]
        rows = decode_pvs(vis)
        text = open(os.path.join(FIXTURE, "maps", name + ".vmf"), "rb").read()
        maps[name] = {
            "exercises": MAPS[name],
            "vmf_sha256": sha(text),
            "header": {"version": bsp["version"], "revision": bsp["revision"]},
            "lumps": rec["tables"][0],
            "pvs": {"clusters": len(rows), "rows": rows, "sha256": sha(vis),
                    "visible_pairs": sum(len(r) for r in rows)},
            "lighting": {"ldr": lighting_summary(bsp["lumps"][L_LIGHTING]["data"]),
                         "hdr": lighting_summary(bsp["lumps"][L_LIGHTING_HDR]["data"])},
            "stages": rec["stages"],
        }
    policy = {
        "threads": "-threads 1 for vbsp, vvis and vrad",
        "aslr": "disabled: every tool runs under `setarch x86_64 -R`",
        "argv": "relative (-game game <map>.vmf|.bsp) from the map directory",
        "environment": ENV,
        "vrad": "-ldr then -hdr on the same BSP (the Linux port rejects -both)",
        "dispinfo_mask": "DISPINFO bytes VBSP never writes are masked: CDispSubNeighbor "
                         "orientation/span/neighbor-span after m_iNeighbor 0xFFFF, "
                         "CDispCornerNeighbors slots >= m_nNeighbors, struct padding",
        "commands": [" ".join([os.path.basename(argv[0])] + argv[1:])
                     for _, argv in stage_argvs(tools_dir, "<map>")],
    }
    findings["compiler_acceptance"] = args_compiler_notes()
    findings["vrad_uninitialized_read"] = {
        "method": "manual, 2026-09-25: valgrind 3.27.1 --track-origins=yes on the post-fix "
                  "vrad -threads 1 -ldr, sky_spot policy VVIS output",
        "observed": "Conditional jump or move depends on uninitialised value(s) at "
                    "BuildSupersampleFaceLights (utils/vrad/lightmap.cpp), 'Uninitialised value "
                    "was created by a stack allocation' in BuildSupersampleFaceLights; no other "
                    "uninitialised-value context in the run",
        "hypothesis": "its stackalloc'd pSampleIntensity holds one value per lightmap texel, "
                      "but ComputeSampleIntensities writes only texels that carry a sample; "
                      "ComputeLightmapGradients reads all eight neighbours, so the "
                      "gradient >= 0.0625 supersampling decision can depend on stale stack "
                      "bytes (pointer values under ASLR, the previous work item's frame with "
                      "several workers). Consistent with the study: -noextra output is "
                      "identical across ASLR and 1/4/32 threads. Not fixed here: the gate "
                      "records legacy bytes, and changing VRAD is a versioned decision.",
    }
    for label, entry in findings["cross_build"].items():
        maps_equal = all(not m["policy_lumps_differing"] for m in entry["maps"].values())
        probe = entry.get("gdb_probe", {}).get("hits", {})
        changed = [k for k in probe if k.startswith("CVRadDispMgr::ClipRayToDisp(") or
                   k.startswith("CVRadDispMgr::ClipRayToDispInLeaf(DispTested_t&, Ray_t const&, "
                                "int)") or "DispRay_Enumerate" in k or
                   k.startswith("CBSPDispRayEnumerator::")]
        entry["verdict"] = {
            "all_policy_lumps_identical": maps_equal,
            "noextra_identical": all(entry.get("noextra_identical", {}).values())
            if entry.get("noextra_identical") else None,
            "changed_functions_hit": {k: probe[k] for k in changed} if probe else None,
            "conclusion": ("identical output; the changed functions are never executed "
                           "(0 hits) while displacement rays are traced, so the fix removed "
                           "undefined behaviour in unreachable code only")
            if maps_equal and probe and not any(probe[k] for k in changed) else
            "see maps/probe: not established",
        }
    expected = collections.OrderedDict([
        ("schema", SCHEMA), ("version", VERSION), ("provenance", block),
        ("primary_build", args.label), ("builds", builds), ("policy", policy),
        ("maps", maps), ("findings", findings)])
    with open(EXPECTED, "w", encoding="utf-8") as stream:
        json.dump(expected, stream, indent=1)
        stream.write("\n")
    files = {}
    for base, _, names in os.walk(FIXTURE):
        for n in sorted(names):
            path = os.path.join(base, n)
            rel = os.path.relpath(path, FIXTURE)
            if rel in ("fixture.json", "expected.json") or "__pycache__" in rel:
                continue
            files[rel] = provenance.file_sha256(path)
    fixture = collections.OrderedDict([
        ("version", VERSION), ("schema", "corpus-fixture/v1"), ("area", "compile"),
        ("description", "Authored VMF maps and a self-contained game root (materials, surface "
                        "properties, empty lights.rad) for the legacy VBSP/VVIS/VRAD "
                        "equivalence suite; expected.json holds the recorded lumps."),
        ("provenance", block), ("expected_sha256", provenance.file_sha256(EXPECTED)),
        ("files", dict(sorted(files.items())))])
    with open(FIXTURE_JSON, "w", encoding="utf-8") as stream:
        json.dump(fixture, stream, indent=1)
        stream.write("\n")
    print("recorded %s (scratch %s)" % (EXPECTED, scratch))
    return 0


def args_compiler_notes():
    """Manual observations (not rerun by `record`): which compilers accept the
    pre-fix `(int)&ctx` casts in utils/vrad/vraddisps.cpp."""
    return {
        "method": "manual, 2026-09-25: the Waf compile line of utils/vrad/vraddisps.cpp in the "
                  "pre-fix build with -fsyntax-only, compiler swapped",
        "g++ 16.2.1 with the tools profile flags (-fpermissive -w)": "accepted",
        "g++ 16.2.1 without -fpermissive": "error: cast from 'CVRadDispMgr::EnumContext_t*' to "
                                           "'int' loses precision [-fpermissive] (lines 565, 578)",
        "clang++ 22.1.8 (with or without -fpermissive)": "error: cast from pointer to smaller "
                                                        "type 'int' loses information "
                                                        "(lines 565, 578)",
        "pre-fix code generation (g++)": "CVRadDispMgr::ClipRayToDisp: lea 0x10(%rsp),%rcx; "
                                         "movslq %ecx,%rcx -- the stack address is truncated "
                                         "to 32 bits and sign-extended; post-fix passes the "
                                         "full pointer",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("mode", nargs="?", default="check", choices=("check", "record"))
    parser.add_argument("--tools", default=DEFAULT_TOOLS,
                        help="directory holding vbsp, vvis, vrad and bin/ (relative to the "
                             "repository root)")
    parser.add_argument("--expected", default=EXPECTED)
    parser.add_argument("--maps", help="comma-separated subset of the fixture maps")
    parser.add_argument("--out", help="scratch directory (default $CONFORMANCE_OUT)")
    parser.add_argument("--seed-fault", choices=("lump-byte", "vis-bit", "vrad-noextra"))
    parser.add_argument("--label", default="post-fix", help="record: primary build label")
    parser.add_argument("--reference-tools", action="append",
                        help="record: another build to compare with the primary")
    parser.add_argument("--reference-label", action="append")
    parser.add_argument("--study-runs", type=int, default=0)
    parser.add_argument("--gdb-probe", action="store_true")
    args = parser.parse_args()
    if args.mode == "record":
        return record(args)
    try:
        return suite(args)
    except (OSError, ValueError, KeyError, RuntimeError) as error:
        print("FAIL suite.error: %s: %s" % (type(error).__name__, error))
        return Checks().report()


if __name__ == "__main__":
    sys.exit(main())
