"Resource/WorkshopItemPanel.res"
{
	"WorkshopItemPanel"
	{
		"ControlName"		"CWorkshopItemPanel"
		"fieldName"		"WorkshopItemPanel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"624"
		"tall"		"80"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"border"		"ButtonBorder"
	}

	"WorkshopImagePanel"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"WorkshopImagePanel"
		"xpos"			"8"
		"ypos"			"8"
		"wide"			"64"
		"tall"			"64"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"scaleProportional" "-1"
		"image"			"hud/vote_no"
		"border"		"ButtonBorder"
	}

	"WorkshopItemTitle"
	{
		"ControlName" "Label"
		"fieldName" "WorkshopItemTitle"
		"xpos"		"88"
		"ypos"		"12"
		"wide"		"408"
		"tall"		"16"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap" "0"
		"tabPosition"		"0"
		"textAlignment"		"west"

		"font" "DefaultBold"
	}

	"WorkshopItemDesc"
	{
		"ControlName" "Label"
		"fieldName" "WorkshopItemDesc"
		"xpos"		"88"
		"ypos"		"34"
		"wide"		"408"
		"tall"		"34"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap" "1"
		"tabPosition"		"0"
		"textAlignment"		"north-west"

		"font" "Default"
	}

	"WorkshopPlayButton"
	{
		"ControlName"		"Button"
		"fieldName"		"WorkshopPlayButton"
		"xpos"		"512"
		"ypos"		"28"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Workshop_Play"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"play"
		"textinsetx"	"6"
		"use_proportional_insets" "1"
	}

	"WorkshopEditButton"
	{
		"ControlName"		"Button"
		"fieldName"		"WorkshopEditButton"
		"xpos"		"512"
		"ypos"		"28"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Workshop_EditItem"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"edit"
		"textinsetx"	"6"
		"use_proportional_insets" "1"
	}

	"WorkshopCheckButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"WorkshopCheckButton"
		"xpos"		"508"
		"ypos"		"28"
		"wide"		"80"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Enabled"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"addon_enabled"
	}

	"UpButton"
	{
		"ControlName"		"Button"
		"fieldName"		"UpButton"
		"xpos"		"592"
		"ypos"		"8"
		"wide"		"24"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"t"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"addon_up"
		"textinsetx"	"6"
		"textinsety"	"2"
		"use_proportional_insets" "1"
		"font"	"MarlettLarge"
	}

	"DownButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DownButton"
		"xpos"		"592"
		"ypos"		"48"
		"wide"		"24"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"u"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"textinsetx"	"6"
		"textinsety"	"1"
		"use_proportional_insets" "1"
		"Command"		"addon_down"
		"font"	"MarlettLarge"
	}
}
