#! /usr/bin/env python
# encoding: utf-8

# render.pass.debug (RFC 0014): what the debug controls draw that no program
# draws (the not-applicable hatch).

top = '.'

def options(opt):
	return

def configure(conf):
	conf.load('strict_cpp20', tooldir='scripts/waifulib')

def build(bld):
	bld.stlib(
		env         = bld.strict_cpp20_env(),
		features    = 'cxx capability_strict',
		arch_module = 'render.pass.debug',
		target      = 'render_pass_debug',
		name        = 'render_pass_debug',
		source      = bld.path.ant_glob('*.cpp'),
		includes    = ['../../../public'],
		use         = ['render_device', 'render_spv'],
		idx         = bld.get_taskgen_count()
	)
