#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'appframework'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp',
	]

	# The window provider: the one module that links the platform SDK (RFC 0001
	# R18). Everything else asks it through ILauncherPlatformServices.
	if bld.env.SDL:
		source += [
			'sdl3mgr.cpp',
			'sdl_window_provider.cpp'
		]


	if bld.env.DEST_OS == 'win32':
		source += [
			'VguiMatSysApp.cpp',
			'WinApp.cpp'
		]
	else:
		source += [
			'posixapp.cpp',#		[$POSIX]
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	defines = []

	libs = ['SDL3'] if bld.env.SDL else []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
