#! /usr/bin/env python
# encoding: utf-8
# render.pass.opaque (RFC 0016 layer 6 feature, K5).

def build(bld):
	bld.stlib(
		env         = bld.strict_cpp20_env(),
		features    = 'cxx capability_strict',
		arch_module = 'render.pass.opaque',
		target      = 'render_pass_opaque',
		name        = 'render_pass_opaque',
		source      = bld.path.ant_glob('*.cpp'),
		includes    = ['../../../public'],
		use         = ['render_scene', 'render_resources', 'render_graph', 'render_device', 'render_spv'],
		idx         = bld.get_taskgen_count()
	)
