#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'video_services'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'videoservices.cpp',
		'provider_catalog_runtime.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','tier1','tier2','tier3','vstdlib']
	if bld.env.VIDEO_BINK:
		defines += ['LINK_VIDEO_BINK']
		libs += ['video_bink']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']
	elif bld.env.DEST_OS == 'darwin':
		libs += ['COREGRAPHICS']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)


	bld.program(
		source = ['../unittests/videoprovidertest/catalog_test.cpp', 'provider_catalog_runtime.cpp'],
		target = 'video_provider_catalog_test',
		name = 'video_provider_catalog_test',
		features = 'cxx cxxprogram',
		includes = includes,
		use = ['tier0'],
		install_path = bld.env.TESTDIR,
		idx = bld.get_taskgen_count()
	)

	bld.program(
		source = ['../unittests/videoprovidertest/catalog_test.cpp', 'provider_catalog_runtime.cpp'],
		target = 'video_service_catalog_test',
		name = 'video_service_catalog_test',
		features = 'cxx cxxprogram',
		includes = includes,
		defines = ['VIDEO_SERVICE_INTEGRATION'],
		use = ['tier0', 'video_services', 'inputsystem'],
		install_path = bld.env.TESTDIR,
		idx = bld.get_taskgen_count()
	)
