#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'stdshader_dx9'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'STDSHADER_DX9_DLL_EXPORT',
		'FAST_MATERIALVAR_ACCESS'
	])

def build(bld):
	source = [
		'builtin_shader_provider.cpp',
		'BaseVSShader.cpp',
		'fixed_state_shaders.cpp',
		'cloak.cpp',
		'cloak_blended_pass_helper.cpp',
		'cloak_dx9_helper.cpp',
		'compositor.cpp',
		'core_dx9.cpp',
		#'debugmorphaccumulator_dx9.cpp',					[$WIN32]
		'DecalBaseTimesLightmapAlphaBlendSelfIllum_dx9.cpp',
		'Engine_Post_dx9.cpp',
		'emissive_scroll_blended_pass_helper.cpp',
		'eye_refract.cpp',
		'eye_refract_helper.cpp',
		'eyes_dx8_dx9_helper.cpp',
		'eyes_dx9.cpp',
		'flesh_interior_blended_pass_helper.cpp',
		'lightmappedgeneric_dx9.cpp',
		'lightmappedgeneric_dx9_helper.cpp',
		'lightmappedpaint_dx9.cpp',
		'lightmappedreflective.cpp',
		'modulate_dx9.cpp',
		'MonitorScreen_dx9.cpp',
		#'morphaccumulate_dx9.cpp',					[$WIN32]
		#'morphweight_dx9.cpp',						[$WIN32]
		'paintblob_dx9.cpp',
		'paintblob_helper.cpp',
		'pbr_dx9.cpp',
		'portal.cpp',
		'portalstaticoverlay.cpp',
		'portal_refract.cpp',
		'portal_refract_helper.cpp',
		'refract.cpp',
		'refract_dx9_helper.cpp',
		'screenspace_general.cpp',
		'shatteredglass.cpp',
		'skin_dx9_helper.cpp',
		'sky_hdr_dx9.cpp',
		'solidenergy_dx9.cpp',
		'solidenergy_dx9_helper.cpp',
		'sprite_dx9.cpp',
		'spritecard.cpp',
		'teeth.cpp',
		'unlitgeneric_dx9.cpp',
		'unlittwotexture_dx9.cpp',
		'vertexlitgeneric_dx9.cpp',
		'vertexlitgeneric_dx9_helper.cpp',
		'water.cpp',
		'weapon_sheen_pass_helper.cpp',
		'wireframe_dx9.cpp',
		'worldtwotextureblend.cpp',
		'worldvertextransition.cpp',
		'worldvertextransition_dx8_helper.cpp',
		'../../public/tier0/memoverride.cpp'
	]
	# The canonical shader binds Vulkan's native world pipeline. DX9 keeps the
	# existing fallback material route in its independently built profile.
	source.append('pbr_metalrough_native.cpp' if bld.env.NATIVE_VULKAN
	              else 'pbr_metalrough_fallback.cpp')

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','shaderlib','tier1','mathlib']

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
