#! /usr/bin/env python
# encoding: utf-8


def options(opt):
	pass


def configure(conf):
	pass


def build(bld):
	bld.program(
		features='cxx',
		source=['test_audio_selection.cpp', '../../engine/audio/device_selection.cpp'],
		target='audio_provider_conformance', name='audio_provider_conformance',
		includes=['../../public'], install_path=None)
