#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'tier0'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('WAF_CFLAGS', conf.env.CFLAGS)
	conf.define('WAF_LDFLAGS', conf.env.LINKFLAGS)
	conf.define('TIER0_DLL_EXPORT',1)
#	conf.define('NO_HOOK_MALLOC',1)

def build(bld):
	source = [
		'foundation_facade.cpp', # R103: Tier 0's private foundation providers
		'assert_dialog.cpp',
		'commandline.cpp',
		'cpu.cpp',
		'cpumonitoring.cpp',
		'cpu_usage.cpp',
		'dbg.cpp',
		'dynfunction.cpp',
		'fasttimer.cpp',
		# 'InterlockedCompareExchange128.masm', [$WIN64]
		'mem.cpp',
		'mem_helpers.cpp',
		'memdbg.cpp',
		'memstd.cpp',
		'memvalidate.cpp',
		'minidump.cpp',
		'module_load_telemetry.cpp',
		'pch_tier0.cpp',
		#'pmc360.cpp',		[$X360]
		'PMELib.cpp',		#[$WINDOWS||$POSIX]
		'progressbar.cpp',
		'security.cpp',
		'systeminformation.cpp',
		'stacktools.cpp',
		'thread.cpp',		#[$WINDOWS||$POSIX]
		'threadtools.cpp',
		'tier0_strtools.cpp',
		'tslist.cpp',
		'vprof.cpp',
		#'../tier1/pathmatch.cpp' # [$LINUXALL]
	]
	
	if bld.env.DEST_OS == 'win32':
		source += [
			'assert_dialog.rc',
			'platform.cpp',
			'pme.cpp',
			'vcrmode.cpp',
			'win32consoleio.cpp'
		]
		if bld.env.DEST_CPU == 'amd64':
			source += [
				'InterlockedCompareExchange128.masm'
			]
	else:
		source += [
			'cpu_posix.cpp',
			'platform_posix.cpp',
			'pme_posix.cpp',
			'vcrmode_posix.cpp'
		]
		if bld.env.DEST_OS == '3ds':
			source += ['../platform/n3ds/compat/n3ds_compat.cpp']
		elif bld.env.DEST_OS == 'emscripten':
			source += ['../platform/wasm/compat/wasm_compat.cpp']

	includes = [
		'.',
		'../public',
		'../public/tier0',
	]

	# tier0/dbg.cpp stamps the engine log with the commit; only tier0 sees it.
	defines = [ 'GIT_COMMIT_HASH="%s"' % bld.env.GIT_VERSION ] if bld.env.GIT_VERSION else []

	if bld.env.DEST_OS == 'win32':
		libs = ['ADVAPI32', 'WS2_32', 'SHELL32', 'OLE32', 'WINMM', 'platform_foundation_win32']
	else:
		libs = ['DL', 'M', 'LOG', 'platform_foundation_legacyabi']
	if bld.env.SDL3:
		libs += ['SDL3']

	install_path = None if bld.env.BUILD_SDK else bld.env.LIBDIR

	# The foundation providers are Tier 0's private implementation (R103):
	# nothing from their archive joins the export list mods link against,
	# std template instantiations included.
	linkflags = []
	if bld.env.DEST_OS not in ( 'win32', 'darwin', 'ios', '3ds' ) and not bld.env.APPLE:
		linkflags = [ '-Wl,--exclude-libs,libplatform_foundation_legacyabi.a' ]

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
