//========= Copyright Valve Corporation, All rights reserved. ============//
//
// The game modules of a statically composed product (Waf
// --static-composition, the iOS composition policy). Every module is linked
// into this program; the engine receives the game's modules here instead of
// opening them by name. Each module's named entry is generated by
// scripts/waifulib/static_composition.py.
//
//=============================================================================//

#include "static_composition.h"

#include "appframework/IAppSystem.h"
#include "appframework/linked_systems.h"
#include "engine/linked_game_modules.h"
#include "game/game_platform_services.h"
#include "scenefilecache/ISceneFileCache.h"
#include "SoundEmitterSystem/isoundemittersystembase.h"
#include "tier0/dbg.h"
#if defined( STATIC_COMPOSITION_VSCRIPT )
#include "vscript/ivscript.h"
#endif

extern "C"
{
	void *StaticModule_client_CreateInterface( const char *pName, int *pReturnCode );
	void *StaticModule_server_CreateInterface( const char *pName, int *pReturnCode );
	void *StaticModule_GameUI_CreateInterface( const char *pName, int *pReturnCode );
}

bool StaticComposition_BindGame()
{
	// The app systems the game modules declare (IClientDLLSharedAppSystems and
	// IServerDLLSharedAppSystems).
	static const LinkedGameAppSystem s_AppSystems[] = {
	    { SOUNDEMITTERSYSTEM_INTERFACE_VERSION, SoundEmitterSystem_Create() },
	    { SCENE_FILE_CACHE_INTERFACE_VERSION, SceneFileCache_Create() },
#if defined( STATIC_COMPOSITION_VSCRIPT )
	    // Portal 2's script manager (game/shared/portal2/portal2_vscript_module.h).
	    { VSCRIPT_INTERFACE_VERSION, VScript_Create() },
#endif
	};

	LinkedGameModules modules;
	modules.client = StaticModule_client_CreateInterface;
	modules.server = StaticModule_server_CreateInterface;
	modules.gameUI = StaticModule_GameUI_CreateInterface;
	modules.appSystems = s_AppSystems;
	modules.appSystemCount = sizeof( s_AppSystems ) / sizeof( s_AppSystems[0] );
	return Engine_BindLinkedGameModules( &modules );
}

static bool BindModule( void *pBinding, const GamePlatformServices &services )
{
	return pBinding && static_cast<IGamePlatformServicesBinding *>( pBinding )->Bind( services );
}

bool StaticComposition_BindPlatformServices( const GamePlatformServices &services )
{
	const char *pVersion = GAME_PLATFORM_SERVICES_BINDING_VERSION;
	return BindModule( StaticModule_client_CreateInterface( pVersion, NULL ), services ) &&
	       BindModule( StaticModule_server_CreateInterface( pVersion, NULL ), services ) &&
	       BindModule( StaticModule_GameUI_CreateInterface( pVersion, NULL ), services );
}
