#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	# The Android application root names the game it launches (-game).
	conf.env.GAMES = conf.options.GAMES

def build(bld):
	if bld.env.ANDROID_SDL3:
		# SDLActivity's native entry: libmain.so exporting SDL_main.
		bld.shlib(
			source   = ['android_main.cpp'],
			target   = 'main',
			name     = PROJECT_NAME,
			features = 'c cxx',
			includes = ['../public', '../public/tier0'],
			defines  = ['ANDROID_DEFAULT_GAME="%s"' % bld.env.GAMES],
			use      = ['launcher', 'tier0', 'SDL3'],
			install_path = bld.env.LIBDIR,
			idx      = bld.get_taskgen_count()
		)
		return
	if bld.env.DEST_OS == 'android':
		return
	if bld.env.DEST_OS == 'ios':
		# The app executable: SDL3 owns main() (SDL_main.h) and starts UIKit;
		# the root links and binds every module (static_composition.cpp).
		bld(
			source   = ['ios_main.cpp', 'static_composition.cpp'],
			target   = PROJECT_NAME,
			name     = PROJECT_NAME,
			features = 'c cxx cxxprogram',
			includes = ['../public', '../public/tier0', '../public/tier1'],
			defines  = ['IOS_DEFAULT_GAME="%s"' % bld.env.GAMES],
			use      = ['launcher', 'client', 'server', 'GameUI', 'scenefilecache',
				'soundemittersystem', 'tier0', 'SDL3'],
			install_path = bld.env.BINDIR,
			idx      = bld.get_taskgen_count()
		)
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []

	if bld.env.STATIC_COMPOSITION:
		# The composition root links every module of the product and binds
		# the game modules to the engine (static_composition.cpp). filesystem
		# and physics come in through the launcher.
		source += ['static_composition.cpp']
		includes += ['../public/tier0', '../public/tier1']
		libs += ['launcher', 'client', 'server', 'GameUI', 'scenefilecache',
			'soundemittersystem']

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

