#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	# The Android application root names the game it launches (-game).
	conf.env.GAMES = conf.options.GAMES

def build(bld):
	if bld.env.ANDROID_SDL3:
		# SDLActivity's native entry: libmain.so exporting SDL_main.
		bld.shlib(
			source   = ['android_main.cpp'],
			target   = 'main',
			name     = PROJECT_NAME,
			features = 'c cxx',
			includes = ['../public', '../public/tier0'],
			defines  = ['ANDROID_DEFAULT_GAME="%s"' % bld.env.GAMES],
			use      = ['launcher', 'tier0', 'SDL3'],
			install_path = bld.env.LIBDIR,
			idx      = bld.get_taskgen_count()
		)
		return
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

