#! /usr/bin/env python
# encoding: utf-8

top = '.'
PROJECT_NAME = 'moduleloadshutdownfixture'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	bld.program(
		source       = [ 'moduleloadshutdownfixture.cpp' ],
		target       = PROJECT_NAME,
		name         = PROJECT_NAME,
		features     = 'c cxx cxxprogram',
		includes     = [ '../../public' ],
		defines      = [],
		use          = [ 'tier0' ],
		lib          = [ 'dl' ] if bld.env.DEST_OS != 'win32' else [],
		install_path = bld.env.TESTDIR,
		subsystem    = bld.env.MSVC_SUBSYSTEM,
		idx          = bld.get_taskgen_count()
	)
