#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'materialsystem'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'DEFINE_MATERIALSYSTEM_INTERFACE',
		'MATERIALSYSTEM_EXPORTS',
		#'PROTECTED_THINGS_ENABLE', # conflicts with stlport
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead'
	])

def build(bld):
	source = [
		'CColorCorrection.cpp',
		'cmaterial.cpp',
		'cmaterial_queuefriendly.cpp',
		'CMaterialSubRect.cpp',
		'cmaterialvar.cpp',
		'cmatnullrendercontext.cpp',
		'colorspace.cpp',
		'ctexture.cpp',
		'../public/filesystem_helpers.cpp',
		'imagepacker.cpp',
		'mat_stub.cpp',
		'materialsystem_global.cpp',
		'morph.cpp',
		'occlusionquerymgr.cpp',
		'shadersystem.cpp',
		'builtin_shader_catalog.cpp',
		'shaderextension_compatibility_host.cpp',
		'legacy_render_backend_provider.cpp',
		'texturemanager.cpp',
		'pch_materialsystem.cpp',
		'cmaterialdict.cpp',
		'cmaterialsystem.cpp',
		'cmatlightmaps.cpp',
		'cmatrendercontext.cpp',
		'cmatqueuedrendercontext.cpp',
		'ctexturecompositor.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common',
		'../'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','mathlib','bitmap','shaderlib','vtf']
	# A client links every backend it can offer and its composition root selects
	# one at runtime (-renderer). Each backend exports its own named entry point,
	# so linking several does not make them shadow each other.
	if bld.env.DEDICATED:
		libs += ['shaderapiempty']
	else:
		libs += ['stdshader_dx9']
		defines += ['LINKED_STANDARD_SHADERS']
		if bld.env.DXVK:
			libs += ['shaderapidx9']
			defines += ['LINKED_DX9_BACKEND']
		if bld.env.NATIVE_VULKAN:
			libs += ['shaderapivulkan']
			defines += ['LINKED_NATIVE_VULKAN_BACKEND']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
