#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs, Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'server'

games = {
	'hl2': ['server_base.vpc', 'server_hl2.vpc'],
	'episodic':['server_base.vpc', 'server_episodic.vpc'],
	'hl2mp': ['server_base.vpc', 'server_hl2mp.vpc'],
	'portal': ['server_base.vpc', 'server_portal.vpc'],
	'portal2': ['server_base.vpc', 'server_portal_base.vpc', 'server_portal2.vpc'],
	'hl1': ['server_base.vpc', 'server_hl1.vpc'],
	'hl1mp': ['server_base.vpc', 'server_hl1mp.vpc'],
	'cstrike': ['server_base.vpc', 'server_cstrike.vpc', 'nav_mesh.vpc'],
	'dod': ['server_base.vpc', 'server_dod.vpc'],
	'tf': [
		'server_base.vpc',
		'server_econ_base.vpc',
		'tf/tf_gcmessages_include.vpc',
		'nav_mesh.vpc',
		'server_tf.vpc'
	]
}

def options(opt):
	return

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )
	if bld.env.GAMES == 'portal2':
		missing = [source for source in game['sources']
		           if not os.path.isfile(os.path.join(bld.path.abspath(), source))]
		if missing and os.environ.get('P2_ALLOW_INCOMPLETE') == '1':
			# Developer opt-in while the target is reconstructed; never the default.
			Logs.warn('Portal 2 server: building without %d missing sources (P2_ALLOW_INCOMPLETE=1)'
			          % len(missing))
			game['sources'] = [source for source in game['sources'] if source not in missing]
		elif missing:
			bld.fatal('Portal 2 server source is incomplete (%d selected files missing): %s'
			          % (len(missing), ', '.join(missing[:8])))

	includes = [
		'.',
		'../shared',
		'../../utils/common',
		'../shared/econ',
		'NextBot',
		'../../common',
		'../../public/tier0',
		'../../public/tier1',
		'../../public'
	]

	defines = []

	libs = ['tier0','particles','dmxloader','tier1','tier2','tier3','mathlib','vstdlib','choreoobjects','steam_api']
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	source = game["sources"] + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	cxxflags = []
	if bld.env.GAMES == 'portal2':
		# The imported Portal 2 sources spell some includes from the source root.
		includes += ['../..']
		# Base-game API the Portal 2 sources expect from their later base game.
		# The VPC $ForceIncludes key is not read by vpc_parser, so apply it here.
		cxxflags += ['-include', bld.path.find_node('../shared/portal2/portal2_base_compat.h').abspath()]
	defines = game["defines"]

	defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		cxxflags = cxxflags,
		defines  = defines,
		install_path = install_path,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
