#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vtexconv'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE', 1)

def build(bld):
	source = [
		'../vtex/vtex_main.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common'
	]

	defines = []

	libs = ['vtex_dll']

	install_path = bld.env.BINDIR
	rpath = []
	if bld.env.DEST_OS == 'darwin':
		rpath = [ '@loader_path/bin' ]
	elif bld.env.DEST_OS != 'win32':
		rpath = [ '$ORIGIN/bin' ]

	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		rpath    = rpath,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
