#!/usr/bin/env python3
"""Frozen legacy Hammer excerpts for parity oracles (RFC 0002, R08).

A parity suite compares a migrated workflow with the legacy code it replaces.
Once the legacy code is retired the comparison still needs that code, so the
suite compiles a frozen copy: exact line ranges of legacy sources at a pinned
git revision, written to one generated include with #line directives back to
the original files. Shadow comparisons use copies (AGENTS.md); the copy is
never edited by hand.

A freeze spec (JSON) names the revision, the output include and each excerpt
(path, first and last line, symbol, sha256 of the excerpt's bytes).

  hammer_legacy_freeze.py write  SPEC   # (re)generate the include from git
  hammer_legacy_freeze.py verify SPEC   # the include equals what git gives,
                                        # and every excerpt's sha256 matches

verify needs the pinned revision in the local history. It prints one
checks-v1 line, so it can run as a conformance suite.
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path( __file__ ).resolve().parents[2]


def git_lines( revision, path ):
	text = subprocess.run( [ 'git', '-C', str( ROOT ), 'show', f'{revision}:{path}' ],
		check=True, capture_output=True ).stdout
	return text.decode( 'latin-1' ).splitlines( keepends=True )


def excerpt_text( revision, excerpt ):
	first, last = excerpt[ 'lines' ]
	lines = git_lines( revision, excerpt[ 'path' ] )
	if first < 1 or last > len( lines ) or first > last:
		raise ValueError( f"{excerpt[ 'path' ]}: lines {first}-{last} out of range" )
	return ''.join( lines[ first - 1:last ] )


def render( spec ):
	out = [
		'// GENERATED by tools/quality/hammer_legacy_freeze.py from\n',
		f"// {spec[ 'spec' ]}; do not edit. Verbatim legacy Hammer source at\n",
		f"// revision {spec[ 'revision' ]}, for the parity oracle only.\n",
	]
	for excerpt in spec[ 'excerpts' ]:
		first, last = excerpt[ 'lines' ]
		out.append( f"\n// {excerpt[ 'symbol' ]}: {excerpt[ 'path' ]}:{first}-{last}\n" )
		out.append( f"#line {first} \"{excerpt[ 'path' ]}\"\n" )
		out.append( excerpt_text( spec[ 'revision' ], excerpt ) )
	return ''.join( out )


def load( spec_path ):
	spec = json.loads( pathlib.Path( spec_path ).read_text() )
	spec[ 'spec' ] = str( pathlib.Path( spec_path ).resolve().relative_to( ROOT ) )
	return spec


def write( spec_path ):
	spec = load( spec_path )
	for excerpt in spec[ 'excerpts' ]:
		excerpt[ 'sha256' ] = hashlib.sha256(
			excerpt_text( spec[ 'revision' ], excerpt ).encode( 'latin-1' ) ).hexdigest()
	( ROOT / spec[ 'output' ] ).write_text( render( spec ), encoding='latin-1' )
	stored = { k: v for k, v in spec.items() if k != 'spec' }
	pathlib.Path( spec_path ).write_text( json.dumps( stored, indent=1 ) + '\n' )
	print( f"wrote {spec[ 'output' ]} ({len( spec[ 'excerpts' ] )} excerpts)" )
	return 0


def verify( spec_path ):
	spec = load( spec_path )
	failures = []
	checks = 0
	for excerpt in spec[ 'excerpts' ]:
		checks += 1
		try:
			text = excerpt_text( spec[ 'revision' ], excerpt )
		except ( subprocess.CalledProcessError, ValueError ) as error:
			failures.append( f"{excerpt[ 'symbol' ]}: {error}" )
			continue
		digest = hashlib.sha256( text.encode( 'latin-1' ) ).hexdigest()
		if digest != excerpt.get( 'sha256' ):
			failures.append( f"{excerpt[ 'symbol' ]}: sha256 {digest} != recorded" )
	checks += 1
	frozen = ROOT / spec[ 'output' ]
	if not failures:
		if not frozen.exists() or frozen.read_text( encoding='latin-1' ) != render( spec ):
			failures.append( f"{spec[ 'output' ]} differs from the pinned excerpts" )
	for failure in failures:
		print( f'FAIL {failure}' )
	print( f'CONFORMANCE {checks} {len( failures )}' )
	return 1 if failures else 0


def main():
	parser = argparse.ArgumentParser( description=__doc__.splitlines()[ 0 ] )
	parser.add_argument( 'action', choices=[ 'write', 'verify' ] )
	parser.add_argument( 'spec' )
	args = parser.parse_args()
	return write( args.spec ) if args.action == 'write' else verify( args.spec )


if __name__ == '__main__':
	sys.exit( main() )
