#!/usr/bin/env python3
"""The engine's per-platform default indirect-light producers (RFC 0011 G8),
generated from the product profiles, which own them.

    python3 tools/quality/indirect_defaults.py            # write the header
    python3 tools/quality/indirect_defaults.py --check    # fail if it is stale

Each game product profile (quality/product_profiles/*.json with a `target`)
may carry

    "indirect_light": {"default_producers": ["sdf", "radiosity", "baked"],
                       "chosen_from": "<the measurements that chose it>"}

`r_indirect_producer auto` (its default) selects the first producer in that
list the map and device offer; `baked` always closes the list, so a map
without the other producers' data still lights. Setting `r_indirect_producer
baked` is the rollback: a setting, no rebuild. The header maps the Android
profile to `ANDROID` builds and the Linux desktop profile to the rest; a
platform with no profile entry (Apple, until R29) defaults to baked.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROFILES = ROOT / "quality" / "product_profiles"
HEADER = ROOT / "engine" / "indirect_light_defaults.h"
PRODUCERS = ("baked", "radiosity", "sdf", "rayquery")
# Platform macro (None: every other build) -> the profile that owns it.
PLATFORMS = (("ANDROID", "portal-android-native-vulkan"),
             (None, "portal-linux-wayland-native-vulkan"))


def producers(profile_id):
    profile = json.loads((PROFILES / (profile_id + ".json")).read_text())
    entry = profile.get("indirect_light", {})
    order = list(entry.get("default_producers", ["baked"]))
    if not order or order[-1] != "baked" or len(set(order)) != len(order) or \
            any(name not in PRODUCERS for name in order):
        raise ValueError("%s: default_producers must name distinct producers of %s and end "
                         "with baked, got %r" % (profile_id, PRODUCERS, order))
    return order


def render():
    lines = ["//========= Copyright Valve Corporation, All rights reserved. ============//",
             "//",
             "// Purpose: The default indirect-light producers per platform (RFC 0011 G8):",
             "//          r_indirect_producer auto takes the first one the map and device",
             "//          offer. Generated by tools/quality/indirect_defaults.py from the",
             "//          product profiles' indirect_light.default_producers; do not edit.",
             "//",
             "//===========================================================================//",
             "",
             "#ifndef ENGINE_INDIRECT_LIGHT_DEFAULTS_H",
             "#define ENGINE_INDIRECT_LIGHT_DEFAULTS_H",
             ""]
    first = True
    for macro, profile_id in PLATFORMS:
        order = producers(profile_id)
        if macro:
            lines.append("#%s defined( %s )" % ("if" if first else "elif", macro))
        else:
            lines.append("#else")
        lines.append("// quality/product_profiles/%s.json" % profile_id)
        lines.append("static const char *const kIndirectDefaultProducers[] = { %s };" %
                     ", ".join('"%s"' % name for name in order))
        first = False
    lines += ["#endif", "", "#endif // ENGINE_INDIRECT_LIGHT_DEFAULTS_H", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not HEADER.is_file() or HEADER.read_text() != text:
            print("%s is stale: run tools/quality/indirect_defaults.py" % HEADER.relative_to(ROOT))
            return 1
        print("indirect-light defaults match the product profiles")
        return 0
    HEADER.write_text(text)
    print("wrote %s" % HEADER.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
