#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(conf):
	conf.load('strict_cpp20', tooldir='scripts/waifulib')

def build(bld):
	strict_env = bld.strict_cpp20_env()
	bld.stlib(
		env=strict_env,
		features='cxx',
		source=['container.cpp'],
		target='vtf_container',
		name='vtf_container',
		arch_module='content.vtf-container',
		includes=['../../public'],
		install_path=None)
