#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
"""Regenerates material_spv.h: the embedded SPIR-V of the native material
shaders that are compiled with options (demo_triangle_spv.h holds the rest),
and material_spv_index.h: each array's content hash and source, which names
the shader modules the backend creates (vulkan_shader_library.cpp).

    python3 materialsystem/shaderapivulkan/shaders/regen_material_spv.py --out DIR
    python3 .../regen_material_spv.py --check --compare-dir DIR
    python3 .../regen_material_spv.py --check-index --compare-dir DIR
    python3 .../regen_material_spv.py --debug-out DIR [--shipped DIR]

Neither header is committed (RFC 0016 K4): the build generates them
(tools/render/shader_artifacts.py headers, into <build>/.../generated/spv/),
and this script is the independent writer the checks compare with. Compiles
with the pinned glslc (quality/toolchain/shader-compiler.json), which
tools/render/shader_toolchain.py locates and verifies. The output is written in
the layout clang-format keeps. --check exits 1 when either header in DIR is not
what the GLSL compiles to. --check-index verifies the index against
material_spv.h in DIR (no compiler).
--debug-out writes, for every array still built from the current GLSL, a
named variant with source-level debug information (glslangValidator -gVS:
NonSemantic.Shader.DebugInfo.100, unoptimized) as DIR/<array>.<hash>.spv,
keyed by the embedded array's hash; `-vkshaderdir DIR` makes the backend use
them (RenderDoc then shows GLSL names and steps source). With --shipped (a
build's generated spv directory) arrays whose GLSL changed since that build
are skipped and reported; without it the current GLSL is what ships.
"""

import argparse
import concurrent.futures
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2] / "tools" / "render"))
import shader_toolchain  # noqa: E402
OUTPUT = "material_spv.h"
INDEX_OUTPUT = "material_spv_index.h"
# (array name, source, extra glslc arguments)
SHADERS = (
    # RFC 0011 G5: the compute conformance suite's program.
    ("g_computeFillSpv", "compute_fill.comp", []),
    # RFC 0011 G7: the probe update traced with ray queries (SPIR-V 1.5), from
    # the one copy of the GLSL (render.pass.indirect, which runs the SDF
    # variant on the core since RFC 0016 K12).
    ("g_rayQueryProbeTraceSpv", "../../../render/pass/indirect/sdf_probe_trace.comp",
     ["--target-env=vulkan1.2", "-DRAY_QUERY"]),
    # render.pbr-brdf.glsl: pbr_brdf.glsl evaluated beside public/render/pbr_brdf.h.
    ("g_pbrBrdfCheckSpv", "pbr_brdf_check.comp", []),
    ("g_presentGammaVertSpv", "present_gamma.vert", []),
    ("g_presentGammaFragSpv", "present_gamma.frag", []),
    # Soft particles: the frame copy's alpha from the copied depth (D3D9 dest alpha).
    ("g_depthToAlphaFragSpv", "depth_to_alpha.frag", []),
    ("g_depthToAlphaMsFragSpv", "depth_to_alpha.frag", ["-DMULTISAMPLE"]),
)

HEADER = """//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: Embedded SPIR-V of the native backend's remaining programs: the
//          present-time monitor gamma pass, the soft-particle depth-to-alpha
//          copy, and the compute suites' programs. GENERATED
//          by shaders/regen_material_spv.py from the GLSL in shaders/; do not edit.
//
//===========================================================================//

#ifndef SHADERAPIVULKAN_MATERIAL_SPV_H
#define SHADERAPIVULKAN_MATERIAL_SPV_H

#include <cstdint>
"""


INDEX_HEADER = """//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: The content hash (FNV-1a 64 over the bytes) and GLSL source of
//          every array in material_spv.h, so the backend names the shader
//          modules it creates and matches debug variants to them
//          (vulkan_shader_library.cpp). GENERATED by
//          shaders/regen_material_spv.py with material_spv.h; do not edit.
//
//===========================================================================//

#ifndef SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H
#define SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H

#include <cstdint>

struct MaterialSpvIndexEntry
{
\tuint64_t hash;
\tconst char *array;
\tconst char *source; // the GLSL file and its compile options
};

"""


def spirv_hash(words):
    """FNV-1a 64 over the little-endian bytes of `words`
    (render_vulkan::SpirvHash in vulkan_shader_library.cpp)."""
    value = 0xCBF29CE484222325
    for word in words:
        for byte in word.to_bytes(4, "little"):
            value = ((value ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value


def describe(source, extra):
    return source + ((" " + " ".join(extra)) if extra else "")


def compile_words(source, extra):
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "shader.spv"
        subprocess.run([shader_toolchain.glslc(), "-O", *extra, str(HERE / source), "-o",
                        str(out)], check=True)
        data = out.read_bytes()
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def debug_arguments(extra):
    """glslc options as glslangValidator's (glslc's default is Vulkan 1.0)."""
    arguments, environment = [], "vulkan1.0"
    for option in extra:
        if option.startswith("-D"):
            arguments.append(option)
        elif option.startswith("--target-env="):
            environment = option.split("=", 1)[1]
        else:
            raise ValueError("no glslangValidator equivalent for glslc option %s" % option)
    # glslc enables #include implicitly; glslangValidator needs the extension.
    return ["-V", "-gVS", "--target-env", environment,
            "-P#extension GL_GOOGLE_include_directive : require"] + arguments


def compile_debug(source, extra):
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "shader.spv"
        result = subprocess.run([shader_toolchain.glslang_validator(), *debug_arguments(extra),
                                 str(HERE / source), "-o", str(out)], capture_output=True,
                                text=True)
        if result.returncode != 0:
            raise RuntimeError("glslangValidator %s failed:\n%s" % (
                describe(source, extra), result.stdout + result.stderr))
        return out.read_bytes()


def parallel(function, items):
    with concurrent.futures.ThreadPoolExecutor(os.cpu_count() or 4) as pool:
        return list(pool.map(lambda item: function(*item), items))


def embedded_arrays(path):
    """{array name: words} as a material_spv.h holds them."""
    arrays, name = {}, None
    for line in pathlib.Path(path).read_text().splitlines():
        match = re.match(r"static const uint32_t (\w+)\[\] = \{$", line)
        if match:
            name = match.group(1)
            arrays[name] = []
        elif name and line == "};":
            name = None
        elif name:
            arrays[name].append(int(line.strip().rstrip(",").rstrip("u"), 16))
    return arrays


# .clang-format's column limit; the index is written in the layout it keeps.
COLUMNS = 100


def macro_line(text):
    """`text` with its continuation backslash at the last column (tabs are 4)."""
    width = len(text.expandtabs(4))
    return text + " " * (COLUMNS - 1 - width) + "\\\n"


def index_text(arrays):
    parts = [INDEX_HEADER, "static const MaterialSpvIndexEntry g_materialSpvIndex[] = {\n"]
    for name, source, extra in SHADERS:
        head = "    { 0x%016xull, \"%s\"," % (spirv_hash(arrays[name]), name)
        tail = "\"%s\" }," % describe(source, extra)
        if len(head) + 1 + len(tail) <= COLUMNS:
            parts.append(head + " " + tail + "\n")
        else:
            parts.append(head + "\n        " + tail + "\n")
    parts.append("};\n\n")
    parts.append("// X( array ) for every array, for suites that include material_spv.h.\n")
    parts.append(macro_line("#define MATERIAL_SPV_ARRAYS( X )"))
    names = [name for name, _, _ in SHADERS]
    parts.extend(macro_line("\tX( %s )" % name) for name in names[:-1])
    parts.append("\tX( %s )\n" % names[-1])
    parts.append("\n#endif // SHADERAPIVULKAN_MATERIAL_SPV_INDEX_H\n")
    return "".join(parts)


def render():
    """(material_spv.h, material_spv_index.h) as the GLSL compiles to them."""
    shader_toolchain.glslc()  # resolve and verify once, before the workers
    compiled = parallel(compile_words, [(source, extra) for _, source, extra in SHADERS])
    parts = [HEADER]
    for (name, source, extra), words in zip(SHADERS, compiled):
        parts.append("\n// %s\n" % describe(source, extra))
        parts.append("static const uint32_t %s[] = {\n" % name)
        parts.extend("    0x%08xu,\n" % word for word in words)
        parts.append("};\n")
    parts.append("\n#endif // SHADERAPIVULKAN_MATERIAL_SPV_H\n")
    return "".join(parts), index_text(dict(zip((n for n, _, _ in SHADERS), compiled)))


def regenerate(out_dir):
    subprocess.run([sys.executable, str(HERE / "gen_pbr_split_sum.py"), "--check"],
                   check=True)
    material, index = render()
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / OUTPUT).write_text(material)
    (out_dir / INDEX_OUTPUT).write_text(index)


def check(compare_dir):
    """1 when a header in compare_dir differs from what the GLSL compiles to."""
    stale = []
    for name, text in zip((OUTPUT, INDEX_OUTPUT), render()):
        path = pathlib.Path(compare_dir) / name
        if not path.is_file() or path.read_text() != text:
            stale.append(str(path))
    for path in stale:
        print("%s is not what the GLSL compiles to; run %s" % (path, pathlib.Path(__file__).name),
              file=sys.stderr)
    return 1 if stale else 0


def check_index(compare_dir):
    arrays = embedded_arrays(pathlib.Path(compare_dir) / OUTPUT)
    missing = [name for name, _, _ in SHADERS if name not in arrays]
    if missing:
        print("material_spv.h lacks %s; regenerate it" % ", ".join(missing), file=sys.stderr)
        return 1
    if (pathlib.Path(compare_dir) / INDEX_OUTPUT).read_text() != index_text(arrays):
        print("%s does not match material_spv.h; regenerate both" % INDEX_OUTPUT,
              file=sys.stderr)
        return 1
    return 0


DEBUG_FILE = re.compile(r"^\w+\.[0-9a-f]{16}\.spv$")


def write_debug(directory, shipped=None):
    """Debug variants of the shipped arrays still built from the current GLSL
    (shipped: a build's generated spv directory; without it the current GLSL
    is what ships); returns the manifest written beside them."""
    directory = pathlib.Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    for old in directory.iterdir():
        if DEBUG_FILE.match(old.name):
            old.unlink()
    arrays = embedded_arrays(pathlib.Path(shipped) / OUTPUT) if shipped else None
    jobs = [(source, extra) for _, source, extra in SHADERS]
    current = parallel(compile_words, jobs)
    debug = parallel(compile_debug, jobs)
    entries = []
    for (name, source, extra), words, spirv in zip(SHADERS, current, debug):
        entry = {"array": name, "source": describe(source, extra)}
        if arrays is not None and arrays.get(name) != words:
            entry["status"] = "stale: material_spv.h was not regenerated after its GLSL changed"
        else:
            entry["hash"] = "%016x" % spirv_hash(words)
            entry["file"] = "%s.%s.spv" % (name, entry["hash"])
            entry["status"] = "written"
            (directory / entry["file"]).write_bytes(spirv)
        entries.append(entry)
    manifest = {"schema": "vulkan-shader-debug/v1", "entries": entries}
    (directory / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help="exit 1 when a header is not what the GLSL compiles to")
    mode.add_argument("--check-index", action="store_true",
                      help="verify material_spv_index.h against material_spv.h")
    mode.add_argument("--debug-out", type=pathlib.Path,
                      help="write the named debug variants to this directory")
    mode.add_argument("--out", type=pathlib.Path,
                      help="write material_spv.h and material_spv_index.h to this directory")
    parser.add_argument("--compare-dir", type=pathlib.Path,
                        help="with --check or --check-index: the headers to compare")
    parser.add_argument("--shipped", type=pathlib.Path,
                        help="with --debug-out: the build's generated spv directory")
    args = parser.parse_args(argv)
    if (args.check or args.check_index) != bool(args.compare_dir):
        parser.error("--check and --check-index need --compare-dir, and only they take it")
    if not (args.check or args.check_index or args.debug_out or args.out):
        parser.error("the build generates the headers; pass --out DIR to write copies")
    if args.check_index:
        return check_index(args.compare_dir)
    try:
        if args.check:
            return check(args.compare_dir)
        if args.debug_out:
            manifest = write_debug(args.debug_out, args.shipped)
            stale = [e for e in manifest["entries"] if e["status"] != "written"]
            print("%d debug shaders in %s" % (len(manifest["entries"]) - len(stale),
                                              args.debug_out))
            for entry in stale:
                print("skipped %s (%s): %s" % (entry["array"], entry["source"], entry["status"]),
                      file=sys.stderr)
            return 0
        regenerate(args.out)
    except shader_toolchain.ToolchainError as error:
        print("regen_material_spv: %s" % error, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
