#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
"""Regenerates legacy_spv.h: the legacy shader ports' SPIR-V and program table.

    python3 materialsystem/shaderapivulkan/shaders/regen_legacy_spv.py [--check [--compare-dir DIR]]

Every shaders/legacy/<name>.vert and <name>.frag becomes the array
g_legacy_<name>_vert / g_legacy_<name>_frag. A pixel stage registers the D3D9
shader pairs it ports with one line each (vulkan_legacy_programs.h):

    // @legacy program=<name> ps=<pixel shader> vs=<vertex shader> vert=<stage>
    //         samplers=<sampler>:<2d|cube|3d>,...  [flags=object_position,...]

`vert` names the shaders/legacy/<stage>.vert the pair draws with; the samplers
are the D3D9 samplers the port reads, in binding order of set 0 (at most sixteen).
Compiles with the pinned glslc (quality/toolchain/shader-compiler.json), which
tools/render/shader_toolchain.py locates and verifies. --check exits 1 when
legacy_spv.h (with --compare-dir, the copy in DIR) is not what the GLSL
compiles to (a GLSL change without a regenerated header).
"""

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2] / "tools" / "render"))
import shader_toolchain  # noqa: E402
SOURCES = HERE / "legacy"
OUTPUT = HERE.parent / "legacy_spv.h"
MAX_SAMPLER_SLOTS = 16
DIMENSIONS = {"2d": "kLegacySampler2D", "cube": "kLegacySamplerCube", "3d": "kLegacySamplerVolume"}
VERTEX_FLAGS = {"object_position": "kLegacyObjectPosition",
                "object_position_extra": "kLegacyObjectPositionExtra"}
PROGRAM_LINE = re.compile(r"^//\s*@legacy\s+(.*)$")

HEADER = """//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: Embedded SPIR-V of the legacy shader ports (shaders/legacy/, ports
//          of stdshader_dx9's HLSL) and their program table, which
//          vulkan_legacy_programs.cpp includes. GENERATED by
//          shaders/regen_legacy_spv.py from the GLSL and its @legacy lines; do
//          not edit.
//
//===========================================================================//

#ifndef SHADERAPIVULKAN_LEGACY_SPV_H
#define SHADERAPIVULKAN_LEGACY_SPV_H

#include <cstdint>

// Generated tables: kept out of clang-format.
// clang-format off
"""


class LegacyError(Exception):
    pass


def compile_words(source):
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "shader.spv"
        subprocess.run([shader_toolchain.glslc(), "-O", "-Werror", "-I", str(SOURCES), str(source),
                        "-o", str(out)], check=True)
        data = out.read_bytes()
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def array_name(stem, stage):
    return "g_legacy_%s_%s" % (stem, stage)


def parse_programs(frag):
    """The @legacy lines of a pixel stage, as dicts."""
    programs = []
    lines = frag.read_text().splitlines()
    for number, line in enumerate(lines, 1):
        match = PROGRAM_LINE.match(line.strip())
        if not match:
            continue
        text = match.group(1)
        # A registration may continue on following comment lines.
        follow = number
        while follow < len(lines) and lines[follow].strip().startswith("//") and \
                "=" in lines[follow] and "@legacy" not in lines[follow]:
            text += " " + lines[follow].strip()[2:]
            follow += 1
        fields = dict(item.split("=", 1) for item in text.split())
        where = "%s:%d" % (frag.name, number)
        for key in ("program", "ps", "vs", "vert"):
            if key not in fields:
                raise LegacyError("%s: @legacy needs %s=" % (where, key))
        if not (SOURCES / (fields["vert"] + ".vert")).is_file():
            raise LegacyError("%s: no legacy/%s.vert" % (where, fields["vert"]))
        samplers = []
        for item in filter(None, fields.get("samplers", "").split(",")):
            sampler, _, dim = item.partition(":")
            if not sampler.isdigit() or not 0 <= int(sampler) < 16 or dim not in DIMENSIONS:
                raise LegacyError("%s: bad sampler %r" % (where, item))
            samplers.append((int(sampler), dim))
        if len(samplers) > MAX_SAMPLER_SLOTS:
            raise LegacyError("%s: more than %d samplers" % (where, MAX_SAMPLER_SLOTS))
        flags = []
        for flag in filter(None, fields.get("flags", "").split(",")):
            if flag not in VERTEX_FLAGS:
                raise LegacyError("%s: unknown flag %r" % (where, flag))
            flags.append(VERTEX_FLAGS[flag])
        programs.append({"name": fields["program"], "ps": fields["ps"], "vs": fields["vs"],
                         "vert": fields["vert"], "frag": frag.stem, "samplers": samplers,
                         "flags": flags, "where": where})
    return programs


def program_table(programs):
    seen = {}
    for program in programs:
        pair = (program["ps"].lower(), program["vs"].lower())
        if pair in seen:
            raise LegacyError("%s: %s/%s is already registered at %s"
                              % (program["where"], program["ps"], program["vs"], seen[pair]))
        seen[pair] = program["where"]
    rows = ["\n// The program table (vulkan_legacy_programs.cpp).\n",
            "#define LEGACY_PROGRAM_TABLE \\\n"]
    for program in sorted(programs, key=lambda p: p["name"]):
        slots = ["{ %d, %s }" % (sampler, DIMENSIONS[dim]) for sampler, dim in program["samplers"]]
        slots += ["{}"] * (MAX_SAMPLER_SLOTS - len(slots))
        rows.append("    { \"%s\", \"%s\", \"%s\", %s, sizeof( %s ), %s, sizeof( %s ), { %s }, %s }, \\\n"
                    % (program["name"], program["ps"], program["vs"],
                       array_name(program["vert"], "vert"), array_name(program["vert"], "vert"),
                       array_name(program["frag"], "frag"), array_name(program["frag"], "frag"),
                       ", ".join(slots), " | ".join(program["flags"]) or "0"))
    # The last row ends the macro.
    rows[-1] = rows[-1][:-len(" \\\n")] + "\n"
    rows.append("\n")
    return "".join(rows)


def render():
    parts = [HEADER]
    programs = []
    sources = sorted(SOURCES.glob("*.vert")) + sorted(SOURCES.glob("*.frag"))
    for source in sorted(sources, key=lambda path: path.name):
        words = compile_words(source)
        parts.append("\n// legacy/%s\n" % source.name)
        parts.append("static const uint32_t %s[] = {\n" % array_name(source.stem, source.suffix[1:]))
        parts.extend("    0x%08xu,\n" % word for word in words)
        parts.append("};\n")
        if source.suffix == ".frag":
            programs += parse_programs(source)
    if not programs:
        raise LegacyError("no @legacy program in %s" % SOURCES)
    parts.append(program_table(programs))
    parts.append("// clang-format on\n\n#endif // SHADERAPIVULKAN_LEGACY_SPV_H\n")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when legacy_spv.h is not what the GLSL compiles to")
    parser.add_argument("--compare-dir", type=pathlib.Path,
                        help="with --check: compare against legacy_spv.h in this directory")
    args = parser.parse_args()
    if args.compare_dir and not args.check:
        parser.error("--compare-dir needs --check")
    try:
        text = render()
    except (LegacyError, shader_toolchain.ToolchainError) as error:
        print("regen_legacy_spv: %s" % error, file=sys.stderr)
        return 2
    if args.check:
        target = args.compare_dir / OUTPUT.name if args.compare_dir else OUTPUT
        current = target.read_text() if target.exists() else ""
        if current != text:
            print("%s is stale; run %s" % (target, pathlib.Path(__file__).name), file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
