#! /usr/bin/env python
# encoding: utf-8
# render.pass.skinning (RFC 0016 layer 6 feature, K6).

def build(bld):
	bld.stlib(
		env         = bld.strict_cpp20_env(),
		features    = 'cxx capability_strict',
		arch_module = 'render.pass.skinning',
		target      = 'render_pass_skinning',
		name        = 'render_pass_skinning',
		source      = bld.path.ant_glob('*.cpp'),
		includes    = ['../../../public'],
		use         = ['render_graph', 'render_device'],
		idx         = bld.get_taskgen_count()
	)
