"Resource/WorkshopUploaderPage.res"
{
	"WorkshopUploaderPage"
	{
		"ControlName"		"CWorkshopUploaderPage"
		"fieldName"		"WorkshopUploaderPage"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"624"
		"tall"		"548"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"PreviewImageLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"PreviewImageLabel"
		Font			DefaultLarge
		"xpos"			"28"
		"ypos"			"16"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_PreviewImage"
		"textAlignment"	"north-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"PreviewImage"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PreviewImage"
		"xpos"		"28"
		"ypos"		"40"
		"wide"		"256"
		"tall"		"256"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"fillcolor"		"0 0 0 240"
	}

	"TitleLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"TitleLabel"
		Font			DefaultLarge
		"xpos"			"312"
		"ypos"			"16"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_Title"
		"textAlignment"	"north-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"Title"
	{
		"ControlName"	"TextEntry"
		"fieldName"		"Title"
		Font			DefaultLarge
		"xpos"			"312"
		"ypos"			"40"
		"wide"			"284"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"DescriptionLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"DescriptionLabel"
		Font			DefaultLarge
		"xpos"			"312"
		"ypos"			"64"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_Description"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"Description"
	{
		"ControlName"	"TextEntry"
		"fieldName"		"Description"
		"xpos"			"312"
		"ypos"			"88"
		"wide"			"284"
		"tall"			"240"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"textAlignment"	"north-east"
		"multiline" "1"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"BrowseImage"
	{
		"ControlName"	"Button"
		"fieldName"		"BrowseImage"
		Font			DefaultLarge
		"xpos"			"28"
		"ypos"			"304"
		"wide"			"256"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_Browse"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"command"		"BrowseImage"
	}

	"AddonTypeLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"AddonTypeLabel"
		Font			DefaultLarge
		"xpos"			"28"
		"ypos"			"336"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_AddonType"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"AddonType"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AddonType"
		"xpos"		"28"
		"ypos"		"360"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

	"VisibilityLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"VisibilityLabel"
		Font			DefaultLarge
		"xpos"			"312"
		"ypos"			"336"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_Visibility"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"tooltiptext"	"#GameUI_Workshop_VisibilityTooltip"
	}

	"Visibility"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Visibility"
		"xpos"		"312"
		"ypos"		"360"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"tooltiptext"	"#GameUI_Workshop_VisibilityTooltip"
	}

//  misyl: Localization is now automatically found and loaded.
//	"AdditionalLocalizationLabel"
//	{
//		"ControlName"	"Label"
//		"fieldName"		"AdditionalLocalizationLabel"
//		Font			DefaultLarge
//		"xpos"			"312"
//		"ypos"			"384"
//		"wide"			"250"
//		"tall"			"24"
//		"autoResize"	"0"
//		"pinCorner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"	"0"
//		"labelText"		"#GameUI_Workshop_Upload_AdditionalLocalization"
//		"textAlignment"	"west"
//		"dulltext"		"0"
//		"brighttext"	"0"
//		"wrap"			"0"
//	}
//
//	"AdditionalLocalization"
//	{
//		"ControlName"		"TextEntry"
//		"fieldName"		"AdditionalLocalization"
//		"xpos"		"312"
//		"ypos"		"408"
//		"wide"		"192"
//		"tall"		"24"
//		"autoResize"		"0"
//		"pinCorner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"3"
//		"textHidden"		"0"
//		"editable"		"1"
//		"wrap" "0"
//		"maxchars"		"-1"
//		"NumericInputOnly"		"0"
//		"unicode"		"0"
//		"tooltiptext"	"#GameUI_Workshop_AdditionalLocalizationTooltip"
//	}

	"StartingMapLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"StartingMapLabel"
		Font			DefaultLarge 
		"xpos"			"28"
		"ypos"			"384"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_StartingMap"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"tooltiptext"	"#GameUI_Workshop_StartingMap"
	}

	"StartingMap"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"StartingMap"
		"xpos"		"28"
		"ypos"		"408"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"1"
		"wrap" "0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"tooltiptext"	"#GameUI_Workshop_StartingMap"
	}

	"ExpansionLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"ExpansionLabel"
		Font			DefaultLarge 
		"xpos"			"312"
		"ypos"			"384"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_Expansion"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"tooltiptext"	"#GameUI_Workshop_ExpansionTooltip"
	}

	"ExpansionButton"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ExpansionButton"
		"xpos"		"312"
		"ypos"		"408"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

	"ContentLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"ContentLabel"
		Font			DefaultLarge 
		"xpos"			"28"
		"ypos"			"432"
		"wide"			"250"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_Workshop_Upload_ContentFolder"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
	}

	"Content"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Content"
		"xpos"		"28"
		"ypos"		"456"
		"wide"		"532"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"1"
		"wrap" "0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

	"ContentButton"
	{
		"ControlName"		"Button"
		"fieldName"		"Content"
		"xpos"		"568"
		"ypos"		"456"
		"wide"		"28"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"1"
		"wrap" "0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"labelText" "..."
		"textAlignment"	"center"
		"command" "BrowseContentFolder"
	}

	"UploadButton"
	{
		"ControlName"		"Button"
		"fieldName"		"UploadButton"
		"xpos"		"28"
		"ypos"		"496"
		"wide"		"568"
		"tall"		"32"
		Font			Default
		"textAlignment"	"center"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"wrap" "0" 
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"command" "DoUpload"
		"labelText" "#GameUI_Workshop_Upload_Upload"
	}

	"Progress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"ProgressBar"
		"xpos"		"28"
		"ypos"		"508"
		"wide"		"568"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"wrap" "0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

}
