#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
"""The legacy ports' pixels a material family is compared with (RFC 0016 K4
"Families match ports").

    python3 tools/render/family_port_pixels.py record --run DIR --family NAME \\
        --out quality/fixtures/render-families/<family>-port-v1.vdf
    python3 tools/render/family_port_pixels.py record-model --run DIR \\
        --family pbr --out quality/fixtures/render-families/pbr-port-v1.vdf

`record` reads a legacy_shader_conformance.py run (DIR/evidence.json and
DIR/pixels.json) of a family's case file
(quality/fixtures/legacy-shaders/families/<family>.vdf). The run must have
passed: every case drawn by its legacy port and matched to the retail D3D9
bytecode (legacy_shader_oracle.py). It writes each case's sampled pixels as
KeyValues text, which the family's GPU suite parses with kvtext, together with
the run's provenance (the case file's sha256, the harness and renderer, the
HDR mode, the tolerance the port was judged at). Refuses a failed run, a run
of another case file, or a case the run did not draw.

`record-model` reads a material_pixel_conformance.py run of a model family
(DIR/evidence.json and DIR/pixels.json; `pbr-model` for the `pbr` family),
which must have passed its oracle (material_pixel_pbr_model.py judges every
pixel against an independent BRDF model). The harness's report describes its
own inputs, so the fixture carries them (textures, materials, quads, and per
case the placement, ambient cube and lights) together with the port's pixels
on a grid of every STRIDE pixels, where the oracle judges a pixel (not near a
quad edge or the horizon). The family suite draws the inputs and compares.
There is no second copy of the case table: the harness
(unittests/shaderextensiontest/material_pixel_modellight.cpp) stays its owner.

The fixture is versioned: a changed case file or port needs a new recording,
reviewed like any other fixture change. Python 3 standard library only.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = "render-family-port-pixels/v1"


class RecordError(Exception):
    pass


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def record(run, family):
    run = Path(run)
    evidence = json.loads((run / "evidence.json").read_text())
    pixels = json.loads((run / "pixels.json").read_text())
    if evidence.get("status") != "pass":
        raise RecordError("the port run did not pass (status %r)" % evidence.get("status"))
    case_file = ROOT / "quality/fixtures/legacy-shaders/families" / (family + ".vdf")
    case_files = [str((ROOT / p).resolve()) for p in evidence.get("case_files", [])]
    if case_files != [str(case_file.resolve())]:
        raise RecordError("the run drew %s, not %s" % (case_files, case_file))
    names = [c["name"] for c in pixels.get("cases", [])]
    if not names:
        raise RecordError("the run drew no case")
    lines = ['// GENERATED by tools/render/family_port_pixels.py record; do not edit.',
             '"FamilyPortPixels"', "{",
             '\t"schema" "%s"' % SCHEMA,
             '\t"family" "%s"' % family,
             '\t"case_file" "%s"' % case_file.relative_to(ROOT).as_posix(),
             '\t"case_file_sha256" "%s"' % sha256(case_file),
             '\t"renderer" "%s"' % evidence.get("renderer", ""),
             '\t"hdr" "%s"' % evidence.get("hdr", ""),
             '\t"harness_sha256" "%s"' % evidence.get("harness_sha256", ""),
             '\t"port_tolerance" "%s"' % evidence.get("tolerance", "")]
    for case in pixels["cases"]:
        lines += ["\t\"case\"", "\t{", '\t\t"name" "%s"' % case["name"]]
        if not case.get("pixels"):
            raise RecordError("case %s has no pixels" % case["name"])
        for pixel in case["pixels"]:
            lines.append('\t\t"pixel" "%d %d %s"' % (pixel["x"], pixel["y"],
                                                      " ".join(str(v) for v in pixel["rgba"])))
        lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n", len(names)


STRIDE = 8
MODEL_FAMILIES = {"pbr": "pbr-model"}


def numbers(values):
    return " ".join(repr(float(v)) if isinstance(v, float) else str(v) for v in values)


def record_model(run, family):
    sys.path.insert(0, str(ROOT / "tools/quality"))
    import material_pixel_frames
    import material_pixel_pbr_model as oracle
    run = Path(run)
    evidence = json.loads((run / "evidence.json").read_text())
    report = json.loads((run / "pixels.json").read_text())
    if family not in MODEL_FAMILIES:
        raise RecordError("no model family %s (known: %s)" % (family, ", ".join(MODEL_FAMILIES)))
    if evidence.get("status") != "pass":
        raise RecordError("the port run did not pass (status %r)" % evidence.get("status"))
    if report.get("family") != MODEL_FAMILIES[family]:
        raise RecordError("the run drew %r, not %r" % (report.get("family"),
                                                        MODEL_FAMILIES[family]))
    width, height = report["frame"]
    lines = ['// GENERATED by tools/render/family_port_pixels.py record-model; do not edit.',
             '"FamilyPortPixels"', "{",
             '\t"schema" "%s"' % SCHEMA,
             '\t"family" "%s"' % family,
             '\t"source" "material_pixel_conformance.py %s"' % MODEL_FAMILIES[family],
             '\t"renderer" "%s"' % report.get("renderer", ""),
             '\t"harness_sha256" "%s"' % evidence.get("harness_sha256", ""),
             '\t"port_tolerance" "%d"' % oracle.PBR_MODEL_TOLERANCE,
             '\t"frame" "%d %d"' % (width, height),
             '\t"quad_z" "%s"' % numbers([report["quad_z"]]),
             '\t"tone_scale" "%s"' % numbers([report["tone_scale"]]),
             '\t"clear" "%s 255"' % numbers(report["clear_probe"]["clear"]),
             '\t"eye" "%s"' % numbers(list(oracle.modellight.EYE_POSITION))]
    for name, texture in sorted(report["textures"].items()):
        w, h = texture["size"]
        rows = texture["row"]
        if len(rows) != w:
            raise RecordError("texture %s: a row of %d texels for width %d" % (name, len(rows), w))
        texels = [c for _ in range(h) for texel in rows for c in texel]
        lines += ['\t"texture"', "\t{", '\t\t"name" "%s"' % name,
                  '\t\t"width" "%d"' % w, '\t\t"height" "%d"' % h,
                  '\t\t"texels" "%s"' % numbers(texels), "\t}"]
    for name, params in sorted(report["materials"].items()):
        lines += ['\t"material"', "\t{", '\t\t"name" "%s"' % name]
        lines += ['\t\t"%s" "%s"' % (key, value) for key, value in params.items()]
        lines.append("\t}")
    for quad in report["quads"]:
        lines += ['\t"quad"', "\t{",
                  '\t\t"corners" "%s"' % numbers([c for corner in quad["corners"] for c in corner]),
                  '\t\t"normal" "%s"' % numbers(quad["normal"]),
                  '\t\t"tangent" "%s"' % numbers(quad["tangent"]), "\t}"]
    count = 0
    for case in report["cases"]:
        model = oracle.PbrCaseModel(report, case)
        rgb = material_pixel_frames.decode_frame(case, report["frame"])
        lines += ['\t"case"', "\t{", '\t\t"name" "%s"' % case["name"],
                  '\t\t"material" "%s"' % case["material"],
                  '\t\t"model_matrix" "%s"' % numbers([v for row in case["model_matrix"] for v in row]),
                  '\t\t"cube" "%s"' % numbers([v for face in case["cube"] for v in face])]
        for light in case["lights"]:
            lines += ['\t\t"light"', "\t\t{", '\t\t\t"type" "%s"' % light["type"]]
            for key in ("color", "position", "direction", "attenuation"):
                lines.append('\t\t\t"%s" "%s"' % (key, numbers(light[key])))
            for key in ("theta", "phi", "falloff"):
                lines.append('\t\t\t"%s" "%s"' % (key, numbers([light[key]])))
            lines.append("\t\t}")
        judged = 0
        for y in range(STRIDE // 2, height, STRIDE):
            for x in range(STRIDE // 2, width, STRIDE):
                if model.expected(x, y) is None:
                    continue
                i = (y * width + x) * 3
                lines.append('\t\t"pixel" "%d %d %s"' % (x, y, numbers(list(rgb[i:i + 3]))))
                judged += 1
        if judged == 0:
            raise RecordError("case %s has no judged pixel" % case["name"])
        lines.append("\t}")
        count += 1
    lines.append("}")
    return "\n".join(lines) + "\n", count


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    rec = sub.add_parser("record")
    rec.add_argument("--run", required=True)
    rec.add_argument("--family", required=True)
    rec.add_argument("--out", required=True)
    model = sub.add_parser("record-model")
    model.add_argument("--run", required=True)
    model.add_argument("--family", required=True)
    model.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == "record-model":
            text, count = record_model(args.run, args.family)
        else:
            text, count = record(args.run, args.family)
    except (RecordError, OSError, ValueError, KeyError) as error:
        print("family_port_pixels: %s" % error, file=sys.stderr)
        return 1
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print("family_port_pixels: %d cases of %s in %s" % (count, args.family, out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
