#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
"""The legacy ports' pixels a material family is compared with (RFC 0016 K4
"Families match ports").

    python3 tools/render/family_port_pixels.py record --run DIR --family NAME \\
        --out quality/fixtures/render-families/<family>-port-v1.vdf

`record` reads a legacy_shader_conformance.py run (DIR/evidence.json and
DIR/pixels.json) of a family's case file
(quality/fixtures/legacy-shaders/families/<family>.vdf). The run must have
passed: every case drawn by its legacy port and matched to the retail D3D9
bytecode (legacy_shader_oracle.py). It writes each case's sampled pixels as
KeyValues text, which the family's GPU suite parses with kvtext, together with
the run's provenance (the case file's sha256, the harness and renderer, the
HDR mode, the tolerance the port was judged at). Refuses a failed run, a run
of another case file, or a case the run did not draw.

The fixture is versioned: a changed case file or port needs a new recording,
reviewed like any other fixture change. Python 3 standard library only.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = "render-family-port-pixels/v1"


class RecordError(Exception):
    pass


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def record(run, family):
    run = Path(run)
    evidence = json.loads((run / "evidence.json").read_text())
    pixels = json.loads((run / "pixels.json").read_text())
    if evidence.get("status") != "pass":
        raise RecordError("the port run did not pass (status %r)" % evidence.get("status"))
    case_file = ROOT / "quality/fixtures/legacy-shaders/families" / (family + ".vdf")
    case_files = [str((ROOT / p).resolve()) for p in evidence.get("case_files", [])]
    if case_files != [str(case_file.resolve())]:
        raise RecordError("the run drew %s, not %s" % (case_files, case_file))
    names = [c["name"] for c in pixels.get("cases", [])]
    if not names:
        raise RecordError("the run drew no case")
    lines = ['// GENERATED by tools/render/family_port_pixels.py record; do not edit.',
             '"FamilyPortPixels"', "{",
             '\t"schema" "%s"' % SCHEMA,
             '\t"family" "%s"' % family,
             '\t"case_file" "%s"' % case_file.relative_to(ROOT).as_posix(),
             '\t"case_file_sha256" "%s"' % sha256(case_file),
             '\t"renderer" "%s"' % evidence.get("renderer", ""),
             '\t"hdr" "%s"' % evidence.get("hdr", ""),
             '\t"harness_sha256" "%s"' % evidence.get("harness_sha256", ""),
             '\t"port_tolerance" "%s"' % evidence.get("tolerance", "")]
    for case in pixels["cases"]:
        lines += ["\t\"case\"", "\t{", '\t\t"name" "%s"' % case["name"]]
        if not case.get("pixels"):
            raise RecordError("case %s has no pixels" % case["name"])
        for pixel in case["pixels"]:
            lines.append('\t\t"pixel" "%d %d %s"' % (pixel["x"], pixel["y"],
                                                      " ".join(str(v) for v in pixel["rgba"])))
        lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n", len(names)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    rec = sub.add_parser("record")
    rec.add_argument("--run", required=True)
    rec.add_argument("--family", required=True)
    rec.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    try:
        text, count = record(args.run, args.family)
    except (RecordError, OSError, ValueError, KeyError) as error:
        print("family_port_pixels: %s" % error, file=sys.stderr)
        return 1
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print("family_port_pixels: %d cases of %s in %s" % (count, args.family, out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
