#!/usr/bin/env python3
"""Frozen render ABI vtable tables (RFC 0016 K0 check `legacy.render-abi`).

    python3 tools/render/render_abi.py check
    python3 tools/render/render_abi.py record [--update]
    python3 tools/render/render_abi.py sensitivity [--cxx g++] [--out DIR]

The recorded table, quality/fixtures/render-abi/render_abi_v1.h, lists every
vtable slot of the frozen material-system and studio-render interfaces in
Itanium (Linux x86_64) order: each virtual method with its full signature,
the this-adjustment a caller through the interface applies, and its function
slot; destructor pairs; secondary vtables; the slot count; and the interface
version string where the header defines one.

The conformance suite (unittests/renderabitest/render_abi_conformance.cpp,
compiled in the legacy-cxx11 dialect) includes that table and derives each
slot from the compiler's own pointer-to-member-function value, so its oracle
is the compiler that builds a frozen consumer, not the header text or this
script.

`record` derives the table from clang's vtable layout dump
(-fdump-vtable-layouts) of the current headers. It refuses to replace an
existing table without --update: the table is the frozen contract, and
changing it is a reviewed ABI decision, never a way to make a check pass.
`check` rederives the table and fails on any difference (a second oracle,
independent of the suite's compiler).

`sensitivity` proves the suite detects ABI changes in each interface: for
every interface it copies the headers to a private include root and seeds
(1) a swap of two adjacent virtual declarations and (2) a virtual appended
after the last one. clang's layout dump must confirm each seed changes that
interface's layout only (swapping two overriders of base virtuals does not,
and such candidates are skipped); the suite, rebuilt against the copy, must
then fail naming that interface and no other. An unmutated copy must pass
(control). It reports a checks-v1 record.

Compiler flags come from the manifest row `legacy.render-abi` and its
profile through the conformance runner's own build function, so this script
holds no second copy of them. The machinery is shared with the VGUI table
(tools/vgui/vgui_abi.py) in tools/quality/abi_table.py; this file holds the
render table's specification.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools", "quality"))
import abi_table  # noqa: E402  (the shared table machinery)

TABLE_VERSION = "render-abi-v1"
TABLE = "quality/fixtures/render-abi/render_abi_v1.h"
SUITE_ID = "legacy.render-abi"

# The frozen interfaces RFC 0016 K0 names: (class, header under public/,
# interface version macro or None). Order is the table's order.
INTERFACES = [
    ("IMaterialSystem", "materialsystem/imaterialsystem.h", "MATERIAL_SYSTEM_INTERFACE_VERSION"),
    ("IMatRenderContext", "materialsystem/imaterialsystem.h", None),
    ("IMaterial", "materialsystem/imaterial.h", None),
    ("IMaterialVar", "materialsystem/imaterialvar.h", None),
    ("ITexture", "materialsystem/itexture.h", None),
    ("IMesh", "materialsystem/imesh.h", None),
    ("IMaterialProxy", "materialsystem/imaterialproxy.h", "IMATERIAL_PROXY_INTERFACE_VERSION"),
    ("IStudioRender", "istudiorender.h", "STUDIO_RENDER_INTERFACE_VERSION"),
]

PREAMBLE = [
    "//========= Copyright Valve Corporation, All rights reserved. ============//",
    "//",
    "// Recorded vtable table %s of the frozen render interfaces (RFC 0016 K0," % TABLE_VERSION,
    "// check legacy.render-abi). Itanium ABI, Linux x86_64. Generated by",
    "// `python3 tools/render/render_abi.py record` from clang's vtable layout",
    "// dump; reviewed and never regenerated to make a check pass. A change here is",
    "// an ABI break of every prebuilt consumer of these interfaces.",
    "//",
    "// X-macro list, included twice by",
    "// unittests/renderabitest/render_abi_conformance.cpp:",
    "//   RENDER_ABI_INTERFACE( I, header, slots )  primary vtable function slots",
    "//   RENDER_ABI_VERSION( I, MACRO, value )     interface version string",
    "//   RENDER_ABI_METHOD( I, adj, slot, signature, Declarer, Name, PmfDeclaration )",
    "//   RENDER_ABI_DESTRUCTOR( I, adj, slot, kind )",
    "//   RENDER_ABI_SECONDARY( I, Base, adj, slots ) secondary vtable of Base",
    "//   RENDER_ABI_END( I )",
    "// `adj` is the this-adjustment of a call through an I*, `slot` the",
    "// function index in the vtable that adjustment selects. PmfDeclaration",
    "// declares RenderAbiPmf, the member pointer type of the recorded",
    "// signature; it is resolved in a class derived from Declarer, where the",
    "// declarer's nested types (printed unqualified) and protected members",
    "// are visible.",
    "//=============================================================================//",
]

AbiError = abi_table.AbiError
split_signature = abi_table.split_signature
parse_layouts = abi_table.parse_layouts
member_declarations = abi_table.member_declarations
seed_swaps = abi_table.seed_swaps
table_blocks = abi_table.table_blocks


def spec():
    """The render table's specification, read from this module's names at
    call time (the tests replace INTERFACES)."""
    return abi_table.Spec(TABLE_VERSION, TABLE, SUITE_ID, "RENDER_ABI", "RenderAbi", "RenderAbiPmf",
                          "RenderAbiSeededExtra", INTERFACES, PREAMBLE)


def table_from_layouts(layouts, versions):
    return abi_table.table_from_layouts(spec(), layouts, versions)


def render_table(table):
    return abi_table.render_table(spec(), table)


def derive_table(root=ROOT, clang="clang++", include_root=None):
    return abi_table.derive_table(spec(), root, clang, include_root)


def compare_tables(recorded, derived):
    return abi_table.compare_tables(spec(), recorded, derived)


def seed_append(text, name):
    return abi_table.seed_append(text, name, "RenderAbiSeededExtra")


def sensitivity(root, cxx, clang, out_dir):
    return abi_table.sensitivity(spec(), root, cxx, clang, out_dir)


def main(argv=None):
    return abi_table.main(spec(), argv, description=__doc__.split("\n\n")[0], root=ROOT,
                          derive=lambda root, clang: derive_table(root, clang),
                          sense=lambda root, cxx, clang, out: sensitivity(root, cxx, clang, out))


if __name__ == "__main__":
    sys.exit(main())
