#!/usr/bin/env python3
# ==== Copyright Valve Corporation, All rights reserved. ======================
"""The VMT corpus (RFC 0016 K4, check render.material.vmt-corpus).

    python3 tools/render/vmt_corpus.py shader-table [--check]
    python3 tools/render/vmt_corpus.py check [--out DIR] [--sanitize address] [--write-fixture]
    python3 tools/render/vmt_corpus.py sensitivity [--out DIR]

shader-table writes render/material/legacy_shaders.inc: every shader name the
product's shader library registers (the stdshader_dx9 sources its wscript
builds, with the native PBRMetalRough) and its DEFINE_FALLBACK_SHADER target.
The importer (render/material/vmt_import.cpp) knows a shader by this list, so
--check fails when the stdshaders sources changed without it.

check walks every VMT of the Portal and Portal 2 content, in each game's search
order (a file shadowed by an earlier search path is the one the game reads):

  portal   ../source-engine/run/runtime (or $SOURCE_PORTAL_RUNTIME):
           portal/portal_pak_dir.vpk, portal/, hl2/hl2_textures_dir.vpk,
           hl2/hl2_misc_dir.vpk, hl2/, platform/platform_misc_dir.vpk,
           platform/
  portal2  the Portal 2 installation ($SOURCE_PORTAL2_STEAM_ROOT, default the
           Steam library): update/, portal2_dlc2/, portal2_dlc1/, portal2/
           (VPK, then loose), platform/

It writes each game's VMTs (and the patch includes they resolve) into a bundle,
compiles the C++ corpus runner (unittests/rendertest/core/material/
vmt_corpus_runner.cpp with render/material and kvtext) with $CONFORMANCE_CXX
or $CXX (g++ by default; --cxx overrides), runs ImportVmt on every VMT and compares the
per-game family counts, the unsupported counts by reason, the list of
unsupported materials and a digest of every material's family with the
versioned fixture quality/fixtures/render-material/vmt-corpus-v1.json. The
runner must finish every VMT: a crash, a timeout or a missing result fails.
--sanitize address builds it with AddressSanitizer and UndefinedBehavior-
Sanitizer. --write-fixture records the current counts (review the diff).

sensitivity seeds a wrong shader mapping (LightmappedGeneric to the unlit
family) into a private copy of the mapping and requires the check to report
the family counts and digest as changed, and requires a truncated corpus
(one VMT removed) to fail its count; both runs must fail for exactly those
reasons.
"""

import argparse
import collections
import hashlib
import io
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "quality"))
from conformance_result import Checks  # noqa: E402
from source_content import VpkDirectory  # noqa: E402

STDSHADERS = ROOT / "materialsystem" / "stdshaders"
TABLE = ROOT / "render" / "material" / "legacy_shaders.inc"
FIXTURE = ROOT / "quality" / "fixtures" / "render-material" / "vmt-corpus-v1.json"
FIXTURE_SCHEMA = "render-vmt-corpus/v1"
BUNDLE_MAGIC = b"VMTBUNDLE1\n"
RUNNER_SOURCES = (
    "kvtext/keyvalues.cpp",
    "render/device/port.cpp",
    "render/material/material.cpp",
    "render/material/vmt_mapping.cpp",
    "render/material/vmt_import.cpp",
    "unittests/rendertest/core/material/vmt_corpus_runner.cpp",
)
INCLUDE_ROOTS = ("public", ".")
# The shader the native product builds for PBRMetalRough (stdshaders/wscript).
NATIVE_EXTRA = "pbr_metalrough_native.cpp"
REGISTRATION = re.compile(
    r"^\s*(BEGIN_VS_SHADER_FLAGS|BEGIN_VS_SHADER|BEGIN_SHADER_FLAGS|BEGIN_SHADER|"
    r"DEFINE_FALLBACK_SHADER)\s*\(\s*(\w+)\s*(?:,\s*(\w+))?", re.M)


class CorpusError(Exception):
    pass


# ---------------------------------------------------------------------------
# The legacy shader table


def product_sources():
    """The stdshader_dx9 sources the product builds, in wscript order."""
    text = (STDSHADERS / "wscript").read_text()
    start = text.index("source = [")
    body = text[start:text.index("\n\t]", start)]
    files = re.findall(r"^\s*'([^']+\.cpp)'", body, re.M)
    return files + [NATIVE_EXTRA]


def shader_names():
    """{lower-case name: lower-case fallback target or ''}, first registration
    winning (as the shader system keeps the first of a name)."""
    names = {}
    for source in product_sources():
        text = (STDSHADERS / source).read_text(errors="replace")
        for match in REGISTRATION.finditer(text):
            name = match.group(2).lower()
            target = (match.group(3) or "").lower() \
                if match.group(1) == "DEFINE_FALLBACK_SHADER" else ""
            names.setdefault(name, target)
    return names


def table_text():
    rows = "".join('\t{ "%s", "%s" },\n' % (name, target)
                   for name, target in sorted(shader_names().items()))
    return ("// GENERATED by tools/render/vmt_corpus.py shader-table: every shader name the\n"
            "// product's shader library registers (the stdshader_dx9 sources in\n"
            "// materialsystem/stdshaders/wscript, with the native PBRMetalRough) and the\n"
            "// shader its DEFINE_FALLBACK_SHADER names. Do not edit.\n"
            "// clang-format off\n"
            "constexpr LegacyShaderName kLegacyShaders[] = {\n" + rows + "};\n"
            "// clang-format on\n")


def command_shader_table(args):
    text = table_text()
    if args.check:
        current = TABLE.read_text() if TABLE.is_file() else ""
        if current != text:
            print("%s is stale; run %s shader-table" % (TABLE.relative_to(ROOT), __file__),
                  file=sys.stderr)
            return 1
        return 0
    TABLE.write_text(text)
    return 0


# ---------------------------------------------------------------------------
# Content


def portal_runtime():
    return Path(os.environ.get("SOURCE_PORTAL_RUNTIME") or
                ROOT.parent / "source-engine" / "run" / "runtime")


def portal2_root():
    return Path(os.environ.get("SOURCE_PORTAL2_STEAM_ROOT") or
                Path.home() / ".local/share/Steam/steamapps/common/Portal 2")


def search_paths(game):
    """[(kind, path)] of a game's search order."""
    if game == "portal":
        base = portal_runtime()
        return [("vpk", base / "portal/portal_pak_dir.vpk"), ("dir", base / "portal"),
                ("vpk", base / "hl2/hl2_textures_dir.vpk"), ("vpk", base / "hl2/hl2_misc_dir.vpk"),
                ("dir", base / "hl2"), ("vpk", base / "platform/platform_misc_dir.vpk"),
                ("dir", base / "platform")]
    base = portal2_root()
    paths = []
    for folder in ("update", "portal2_dlc2", "portal2_dlc1", "portal2"):
        paths += [("vpk", base / folder / "pak01_dir.vpk"), ("dir", base / folder)]
    paths += [("dir", base / "platform")]
    return paths


class Game:
    """A game's files in search order: the first layer holding a path wins."""

    def __init__(self, name):
        self.name = name
        self.layers = []
        for kind, path in search_paths(name):
            if kind == "vpk" and path.is_file():
                self.layers.append((kind, path, VpkDirectory(str(path))))
            elif kind == "dir" and path.is_dir():
                self.layers.append((kind, path, None))
        if not any(kind == "vpk" for kind, _, _ in self.layers):
            raise CorpusError("no %s content (searched %s)" % (
                name, ", ".join(str(p) for _, p in search_paths(name))))

    def vmts(self):
        """Every materials/**.vmt path, lower case, each once."""
        found = set()
        for kind, path, vpk in self.layers:
            if kind == "vpk":
                found.update(p for p in vpk.entries if p.startswith("materials/")
                             and p.endswith(".vmt"))
            elif (path / "materials").is_dir():
                for file in (path / "materials").rglob("*"):
                    if file.is_file() and file.name.lower().endswith(".vmt"):
                        found.add(str(file.relative_to(path)).replace(os.sep, "/").lower())
        return sorted(found)

    def read(self, relative):
        relative = relative.lower()
        for kind, path, vpk in self.layers:
            if kind == "vpk":
                data = vpk.read(relative)
                if data is not None:
                    return data
            else:
                data = read_loose(path, relative)
                if data is not None:
                    return data
        return None


def read_loose(base, relative):
    """A loose file by its lower-case path (the file system is case-blind)."""
    current = base
    for part in relative.split("/"):
        if not current.is_dir():
            return None
        match = next((child for child in current.iterdir() if child.name.lower() == part), None)
        if match is None:
            return None
        current = match
    return current.read_bytes() if current.is_file() else None


PATCH_INCLUDE = re.compile(rb'"?include"?\s+"([^"]+)"', re.I)


def write_bundle(game, path, drop=None):
    """The game's VMTs and the files their patch includes name. Returns the
    material paths (the runner imports these; includes are only resolved)."""
    materials = [vmt for vmt in game.vmts() if vmt != drop]
    files, pending = {}, list(materials)
    while pending:
        relative = pending.pop()
        if relative in files:
            continue
        data = game.read(relative)
        if data is None:
            continue
        files[relative] = data
        for match in PATCH_INCLUDE.finditer(data):
            include = match.group(1).decode("utf-8", "replace").replace("\\", "/").lower()
            pending.append(include.lstrip("/"))
    with open(path, "wb") as out:
        out.write(BUNDLE_MAGIC)
        for relative in sorted(files):
            data = files[relative]
            flag = b"M" if relative in materials else b"I"
            out.write(b"%s %d %d\n" % (flag, len(relative.encode()), len(data)))
            out.write(relative.encode() + b"\n" + data + b"\n")
    return materials


# ---------------------------------------------------------------------------
# The runner


COMPILER = None  # --cxx


def compiler():
    return COMPILER or os.environ.get("CONFORMANCE_CXX") or os.environ.get("CXX") or "g++"


def build_runner(out, sanitize=None, replaced=None):
    """Compiles the runner; `replaced` maps a source to a seeded copy."""
    replaced = replaced or {}
    binary = Path(out) / "vmt_corpus_runner"
    flags = ["-std=c++20", "-O2", "-Wall", "-Wextra", "-Werror", "-g"]
    if sanitize == "address":
        flags += ["-fsanitize=address,undefined", "-fno-omit-frame-pointer",
                  "-fno-sanitize-recover=all"]
    includes = [arg for root in INCLUDE_ROOTS for arg in ("-I", str(ROOT / root))]
    sources = [str(replaced.get(s, ROOT / s)) for s in RUNNER_SOURCES]
    argv = [compiler(), *flags, *includes, *sources, "-o", str(binary)]
    result = subprocess.run(argv, capture_output=True, text=True)
    if result.returncode != 0:
        raise CorpusError("building the runner failed:\n%s" % (result.stdout + result.stderr)[-3000:])
    return binary


def run_runner(binary, bundle, timeout=900):
    env = dict(os.environ)
    env.setdefault("ASAN_OPTIONS", "detect_leaks=1")
    result = subprocess.run([str(binary), str(bundle)], capture_output=True, text=True,
                            timeout=timeout, env=env)
    records = []
    for line in result.stdout.splitlines():
        if line.startswith("{"):
            records.append(json.loads(line))
    return result.returncode, records, result.stderr


# ---------------------------------------------------------------------------
# Summaries


def summarize(records):
    families = collections.Counter()
    unsupported = collections.Counter()
    unsupported_list = []
    unmapped = collections.defaultdict(collections.Counter)
    digest = hashlib.sha256()
    for record in sorted(records, key=lambda r: r["path"]):
        if record["status"] == "ok":
            families[record["family"]] += 1
            outcome = record["family"]
            for key in record.get("unmapped", []):
                unmapped[record["family"]][key] += 1
        else:
            unsupported[record["status"]] += 1
            unsupported_list.append("%s: %s (%s)" % (record["path"], record["status"],
                                                     record["detail"]))
            outcome = "unsupported:" + record["status"]
        digest.update(("%s\t%s\t%s\n" % (record["path"], outcome,
                                          record.get("shader", ""))).encode())
    return {
        "materials": len(records),
        "families": dict(sorted(families.items())),
        "unsupported": dict(sorted(unsupported.items())),
        "unsupported_materials": unsupported_list,
        "digest": digest.hexdigest(),
    }, {family: counter.most_common(25) for family, counter in sorted(unmapped.items())}


def compare(checks, game, summary, expected):
    if not checks.check(expected is not None, "%s.fixture" % game,
                        "the fixture has no %s entry" % game):
        return
    checks.equal(summary["materials"], expected["materials"], "%s.materials" % game)
    checks.equal(summary["families"], expected["families"], "%s.families" % game)
    checks.equal(summary["unsupported"], expected["unsupported"], "%s.unsupported" % game)
    missing = sorted(set(expected["unsupported_materials"]) - set(summary["unsupported_materials"]))
    extra = sorted(set(summary["unsupported_materials"]) - set(expected["unsupported_materials"]))
    checks.check(not missing and not extra, "%s.unsupported-materials" % game,
                 "no longer unsupported: %s; newly unsupported: %s" % (missing[:5], extra[:5]))
    checks.equal(summary["digest"], expected["digest"], "%s.family-digest" % game)


def corpus_run(checks, out, sanitize=None, mapping_patch=None, drop=None, write_fixture=False):
    """Build, run and compare; returns the evidence."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    evidence = {"schema": "render-vmt-corpus-evidence/v1", "compiler": compiler(),
                "sanitize": sanitize, "games": {}}
    table_ok = table_text() == (TABLE.read_text() if TABLE.is_file() else "")
    checks.check(table_ok, "shader-table.current",
                 "render/material/legacy_shaders.inc is stale; run vmt_corpus.py shader-table")
    replaced = mapping_patch(out / "seeded") if mapping_patch else None
    try:
        binary = build_runner(out, sanitize, replaced)
    except CorpusError as error:
        checks.check(False, "runner.builds", str(error))
        return evidence
    checks.check(True, "runner.builds")
    fixture = json.loads(FIXTURE.read_text()) if FIXTURE.is_file() and not write_fixture else None
    recorded = {"schema": FIXTURE_SCHEMA, "profile": "native Vulkan (VmtProfile defaults)",
                "games": {}}
    for name in ("portal", "portal2"):
        try:
            game = Game(name)
        except CorpusError as error:
            checks.check(False, "%s.content" % name, str(error))
            continue
        bundle = out / ("%s.bundle" % name)
        materials = write_bundle(game, bundle, drop if name == "portal" else None)
        try:
            status, records, stderr = run_runner(binary, bundle)
        except subprocess.TimeoutExpired:
            checks.check(False, "%s.runner-finishes" % name, "timed out")
            continue
        (out / ("%s.runner.stderr" % name)).write_text(stderr)
        (out / ("%s.records.jsonl" % name)).write_text(
            "".join(json.dumps(r, sort_keys=True) + "\n" for r in records))
        checks.check(status == 0, "%s.runner-exits-0" % name,
                     "exit %d: %s" % (status, stderr.strip()[-800:]))
        seen = {r["path"] for r in records}
        checks.check(seen == set(materials), "%s.every-material-reported" % name,
                     "%d of %d materials reported" % (len(seen & set(materials)), len(materials)))
        summary, unmapped = summarize(records)
        evidence["games"][name] = dict(summary, unmapped_top=unmapped)
        recorded["games"][name] = summary
        if not write_fixture:
            compare(checks, name, summary, (fixture or {}).get("games", {}).get(name))
    if write_fixture:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(recorded, indent=1) + "\n")
        print("wrote %s" % FIXTURE.relative_to(ROOT))
    return evidence


# ---------------------------------------------------------------------------
# Seeded faults


SEEDED_FROM = '{ "lightmappedgeneric", "lightmapped",'
SEEDED_TO = '{ "lightmappedgeneric", "unlit",'


def seed_wrong_mapping(seeded_root):
    """A copy of vmt_mapping.cpp (with the table it includes) that maps
    LightmappedGeneric to unlit; returns the runner's replaced sources."""
    seeded = Path(seeded_root) / "render" / "material"
    seeded.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(TABLE, seeded / TABLE.name)
    relative = "render/material/vmt_mapping.cpp"
    text = (ROOT / relative).read_text()
    if SEEDED_FROM not in text:
        raise CorpusError("the seeded row %r is not in vmt_mapping.cpp" % SEEDED_FROM)
    (seeded / "vmt_mapping.cpp").write_text(text.replace(SEEDED_FROM, SEEDED_TO, 1))
    return {relative: seeded / "vmt_mapping.cpp"}


def failed_names(checks):
    return {result["name"] for result in checks.results if not result["ok"]}


class RecordingChecks(Checks):
    def __init__(self, stream=None):
        super().__init__(stream)
        self.results = []

    def check(self, condition, name, detail=""):
        self.results.append({"name": name, "ok": bool(condition)})
        return super().check(condition, name, detail)


def command_check(args):
    checks = RecordingChecks()
    out = Path(args.out) if args.out else Path(tempfile.mkdtemp(prefix="vmt-corpus-"))
    evidence = corpus_run(checks, out, args.sanitize, write_fixture=args.write_fixture)
    for game, summary in evidence["games"].items():
        print("%s: %d materials, families %s, unsupported %s" % (
            game, summary["materials"], summary["families"], summary["unsupported"]))
    (out / "vmt-corpus-evidence.json").write_text(json.dumps(evidence, indent=1) + "\n")
    return checks.report()


def command_sensitivity(args):
    checks = Checks()
    out = Path(args.out) if args.out else Path(tempfile.mkdtemp(prefix="vmt-corpus-"))
    runs = {}
    for name, options in (("wrong-mapping", {"mapping_patch": seed_wrong_mapping}),
                          ("dropped-material", {"drop": "materials/concrete/concretefloor001a.vmt"})):
        stream = io.StringIO()
        run = RecordingChecks(stream)
        corpus_run(run, out / name, **options)
        (out / (name + ".log")).write_text(stream.getvalue())
        runs[name] = failed_names(run)
    wrong = runs["wrong-mapping"]
    for game in ("portal", "portal2"):
        checks.check("%s.families" % game in wrong, "wrong-mapping.%s.families" % game,
                     "LightmappedGeneric mapped to unlit passed")
        checks.check("%s.family-digest" % game in wrong, "wrong-mapping.%s.digest" % game,
                     "LightmappedGeneric mapped to unlit passed")
    checks.check(wrong <= {"%s.%s" % (g, c) for g in ("portal", "portal2")
                           for c in ("families", "family-digest")},
                 "wrong-mapping.only-seeded", "also failed: %s" % sorted(wrong))
    dropped = runs["dropped-material"]
    checks.check("portal.materials" in dropped, "dropped-material.detected",
                 "a corpus one VMT short passed")
    checks.check(dropped <= {"portal.materials", "portal.families", "portal.family-digest"},
                 "dropped-material.only-seeded", "also failed: %s" % sorted(dropped))
    return checks.report()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)
    table_parser = commands.add_parser("shader-table", help="write the legacy shader table")
    table_parser.add_argument("--check", action="store_true")
    table_parser.set_defaults(run=command_shader_table)
    check_parser = commands.add_parser("check", help="the render.material.vmt-corpus gate")
    check_parser.add_argument("--out")
    check_parser.add_argument("--sanitize", choices=("address",))
    check_parser.add_argument("--write-fixture", action="store_true")
    check_parser.add_argument("--cxx", help="the compiler (default $CONFORMANCE_CXX, $CXX, g++)")
    check_parser.set_defaults(run=command_check)
    sensitivity_parser = commands.add_parser("sensitivity", help="the check against seeded faults")
    sensitivity_parser.add_argument("--out")
    sensitivity_parser.set_defaults(run=command_sensitivity)
    args = parser.parse_args(argv)
    global COMPILER
    COMPILER = getattr(args, "cxx", None)
    try:
        return args.run(args)
    except CorpusError as error:
        print("vmt_corpus: %s" % error, file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
