#! /usr/bin/env python
# encoding: utf-8

from gettext import install
from waflib import Utils
import os, sys

top = '.'
PROJECT_NAME = 'inputsystem'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('VERSION_SAFE_STEAM_API_INTERFACES',1)

def build(bld):
	source = [
		'inputsystem.cpp',
		'joystick_sdl.cpp',
		'touch_sdl.cpp',
		'gyro_math.cpp',
		'gyro_sdl.cpp',
		'gyro_sensor.cpp',
		'vibrator_device.cpp',
		'vibrator_policy.cpp',
		'vibrator_sdl.cpp',
		'key_translation.cpp',
		'steamcontroller.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'novint.cpp'
		]

	includes = [
		'.',
		'../common',
		'../public',
		'../public/tier0'
	]

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','SDL2','steam_api']

	# The gyroscope reads the NDK sensor queue (gyro_sensor.cpp).
	if bld.env.ANDROID_SDL3:
		libs += ['ANDROID']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

	if bld.env.SDL3:
		bld.program(
			source = [ '../unittests/sdl3test/voice_record_test.cpp' ],
			target = 'sdl3_voice_record_test',
			name = 'sdl3_voice_record_test',
			features = 'cxx cxxprogram',
			includes = includes + [ '../public/engine/audio' ],
			use = [ 'tier0', 'SDL2' ],
			install_path = bld.env.TESTDIR,
			idx = bld.get_taskgen_count()
		)
