"Resource\OptionsSubMouse.res"
{
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"46"
		"ypos"		"186"
		"wide"		"385"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1081"
		"ypos"		"390"
		"wide"		"300"
		"tall"		"420"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
	"JoyScaleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"JoyScaleLabel"
		"xpos"		"38"
		"ypos"		"19"
		"wide"		"179"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gamepad_JoystickSensitivity"
		"textAlignment"		"west"
		"associate"		"JoyScale"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
	}
	"JoyScale"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"JoyScale"
		"xpos"		"38"
		"ypos"		"43"
		"wide"		"260"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Gamepad_JoystickSensitivity_Low"
		"rightText"		"#GameUI_Gamepad_JoystickSensitivity_High"
	}
	"AutoaimLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AutoaimLabel"
		"xpos"		"38"
		"ypos"		"92"
		"wide"		"179"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AimAssist"
		"textAlignment"		"west"
		"associate"		"Autoaim"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"Default"		"1"
	}
	"Autoaim"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Autoaim"
		"xpos"		"38"
		"ypos"		"116"
		"wide"		"175"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
		"tooltiptext"		"#GameUI_AimAssist_Hint"
	}
	"AutoaimScaleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AutoaimScaleLabel"
		"xpos"		"38"
		"ypos"		"165"
		"wide"		"179"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AimAssistScale"
		"tooltiptext"		"#GameUI_AimAssistScale_Hint"
		"textAlignment"		"west"
		"associate"		"AutoaimScale"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
	}
	"AutoaimScale"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"AutoaimScale"
		"xpos"		"38"
		"ypos"		"189"
		"tooltiptext"		"#GameUI_AimAssistScale_Hint"
		"wide"		"260"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"leftText"		"#GameUI_AimAssistScale_Low"
		"rightText"		"#GameUI_AimAssistScale_High"
	}
	"WeaponSelectionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WeaponSelectionLabel"
		"xpos"		"38"
		"ypos"		"238"
		"wide"		"179"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gamepad_WeaponSelection"
		"textAlignment"		"west"
		"associate"		"WeaponSelection"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"Default"		"1"
	}
	"WeaponSelection"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"WeaponSelection"
		"xpos"		"38"
		"ypos"		"262"
		"wide"		"175"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SteamInput"
	{
		"ControlName"		"Button"
		"fieldName"		"SteamInput"
		"xpos"		"240"
		"ypos"		"262"
		"wide"		"240"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#GameUI_Open_SteamInput"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"OpenSteamInput"
	}
}
